
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.AgencyManagementModule
{
    partial class AgentPlanningSearchView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.AgencyManagementModule.AgentPlanningSearchViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AgentPlanningSearchView));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle15 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle16 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle17 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle18 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle19 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle20 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle21 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            this.portionSearchGroupBox = new System.Windows.Forms.GroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.lineCodeText = new System.Windows.Forms.MaskedTextBox();
            this.peaNameText = new System.Windows.Forms.TextBox();
            this.portionSearchBt = new System.Windows.Forms.Button();
            this.peaCodeText = new System.Windows.Forms.MaskedTextBox();
            this.portionSearchImgHint = new System.Windows.Forms.PictureBox();
            this.peaCodeImgHint = new System.Windows.Forms.PictureBox();
            this.peaCodeSearchBt = new System.Windows.Forms.Button();
            this.agentSearchText = new System.Windows.Forms.MaskedTextBox();
            this.agentSearchBt = new System.Windows.Forms.Button();
            this.portionSearchGridView = new System.Windows.Forms.DataGridView();
            this.agentAssignmentGBox = new System.Windows.Forms.GroupBox();
            this.agentStatusText = new System.Windows.Forms.TextBox();
            this.agentStatusLabel = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.agentType = new System.Windows.Forms.TextBox();
            this.agentNameLabel = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.depositLabel = new System.Windows.Forms.Label();
            this.depositText = new System.Windows.Forms.TextBox();
            this.agentAddressText = new System.Windows.Forms.TextBox();
            this.agentNameText = new System.Windows.Forms.TextBox();
            this.pSearchResultGBox = new System.Windows.Forms.GroupBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.removeBt = new System.Windows.Forms.Button();
            this.clearBt = new System.Windows.Forms.Button();
            this.saveBt = new System.Windows.Forms.Button();
            this.btnSelectAll = new System.Windows.Forms.Button();
            this.btnCancelAll = new System.Windows.Forms.Button();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn3 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn4 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn5 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn6 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn7 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn8 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn9 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn10 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn11 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn12 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn13 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.CheckMark = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.AdvPayment = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.BranchId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.LineId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.NumberOfUser = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.PortionDesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.AgentLongName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.AgencyHelp = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.validFrom = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.validTo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.AgentId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TravelHelp = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.portionSearchGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.portionSearchImgHint)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.peaCodeImgHint)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.portionSearchGridView)).BeginInit();
            this.agentAssignmentGBox.SuspendLayout();
            this.pSearchResultGBox.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // portionSearchGroupBox
            // 
            this.portionSearchGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.portionSearchGroupBox.Controls.Add(this.label2);
            this.portionSearchGroupBox.Controls.Add(this.lineCodeText);
            this.portionSearchGroupBox.Controls.Add(this.peaNameText);
            this.portionSearchGroupBox.Controls.Add(this.portionSearchBt);
            this.portionSearchGroupBox.Controls.Add(this.peaCodeText);
            this.portionSearchGroupBox.Controls.Add(this.portionSearchImgHint);
            this.portionSearchGroupBox.Controls.Add(this.peaCodeImgHint);
            this.portionSearchGroupBox.Controls.Add(this.peaCodeSearchBt);
            this.portionSearchGroupBox.Location = new System.Drawing.Point(19, 127);
            this.portionSearchGroupBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.portionSearchGroupBox.Name = "portionSearchGroupBox";
            this.portionSearchGroupBox.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.portionSearchGroupBox.Size = new System.Drawing.Size(984, 95);
            this.portionSearchGroupBox.TabIndex = 0;
            this.portionSearchGroupBox.TabStop = false;
            this.portionSearchGroupBox.Text = "ค้นหารายการสายการเก็บเงิน";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(372, 30);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(84, 16);
            this.label2.TabIndex = 32;
            this.label2.Text = "ชื่อการไฟฟ้า :";
            // 
            // lineCodeText
            // 
            this.lineCodeText.Enabled = false;
            this.lineCodeText.Location = new System.Drawing.Point(161, 59);
            this.lineCodeText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.lineCodeText.Name = "lineCodeText";
            this.lineCodeText.Size = new System.Drawing.Size(776, 23);
            this.lineCodeText.TabIndex = 6;
            this.lineCodeText.KeyDown += new System.Windows.Forms.KeyEventHandler(this.lineCodeText_KeyDown);
            // 
            // peaNameText
            // 
            this.peaNameText.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.peaNameText.Location = new System.Drawing.Point(460, 28);
            this.peaNameText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.peaNameText.Name = "peaNameText";
            this.peaNameText.ReadOnly = true;
            this.peaNameText.Size = new System.Drawing.Size(504, 23);
            this.peaNameText.TabIndex = 26;
            this.peaNameText.TextChanged += new System.EventHandler(this.peaNameText_TextChanged);
            // 
            // portionSearchBt
            // 
            this.portionSearchBt.Enabled = false;
            this.portionSearchBt.Image = ((System.Drawing.Image)(resources.GetObject("portionSearchBt.Image")));
            this.portionSearchBt.Location = new System.Drawing.Point(20, 57);
            this.portionSearchBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.portionSearchBt.Name = "portionSearchBt";
            this.portionSearchBt.Size = new System.Drawing.Size(129, 28);
            this.portionSearchBt.TabIndex = 7;
            this.portionSearchBt.Text = "สายการเก็บเงิน";
            this.portionSearchBt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.portionSearchBt.UseVisualStyleBackColor = true;
            this.portionSearchBt.Click += new System.EventHandler(this.portionSearchBt_Click);
            // 
            // peaCodeText
            // 
            this.peaCodeText.Enabled = false;
            this.peaCodeText.Location = new System.Drawing.Point(159, 26);
            this.peaCodeText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.peaCodeText.Mask = "A00000";
            this.peaCodeText.Name = "peaCodeText";
            this.peaCodeText.Size = new System.Drawing.Size(178, 23);
            this.peaCodeText.TabIndex = 4;
            this.peaCodeText.KeyDown += new System.Windows.Forms.KeyEventHandler(this.peaCodeText_KeyDown);
            // 
            // portionSearchImgHint
            // 
            this.portionSearchImgHint.Image = ((System.Drawing.Image)(resources.GetObject("portionSearchImgHint.Image")));
            this.portionSearchImgHint.Location = new System.Drawing.Point(941, 59);
            this.portionSearchImgHint.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.portionSearchImgHint.Name = "portionSearchImgHint";
            this.portionSearchImgHint.Size = new System.Drawing.Size(23, 25);
            this.portionSearchImgHint.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.portionSearchImgHint.TabIndex = 10;
            this.portionSearchImgHint.TabStop = false;
            this.portionSearchImgHint.Click += new System.EventHandler(this.portionSearchImgHint_Click);
            // 
            // peaCodeImgHint
            // 
            this.peaCodeImgHint.Image = ((System.Drawing.Image)(resources.GetObject("peaCodeImgHint.Image")));
            this.peaCodeImgHint.Location = new System.Drawing.Point(343, 26);
            this.peaCodeImgHint.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.peaCodeImgHint.Name = "peaCodeImgHint";
            this.peaCodeImgHint.Size = new System.Drawing.Size(23, 25);
            this.peaCodeImgHint.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.peaCodeImgHint.TabIndex = 9;
            this.peaCodeImgHint.TabStop = false;
            this.peaCodeImgHint.Click += new System.EventHandler(this.peaCodeImgHint_Click);
            // 
            // peaCodeSearchBt
            // 
            this.peaCodeSearchBt.Enabled = false;
            this.peaCodeSearchBt.Image = ((System.Drawing.Image)(resources.GetObject("peaCodeSearchBt.Image")));
            this.peaCodeSearchBt.Location = new System.Drawing.Point(20, 23);
            this.peaCodeSearchBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.peaCodeSearchBt.Name = "peaCodeSearchBt";
            this.peaCodeSearchBt.Size = new System.Drawing.Size(128, 28);
            this.peaCodeSearchBt.TabIndex = 5;
            this.peaCodeSearchBt.Text = "การไฟฟ้า      ";
            this.peaCodeSearchBt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.peaCodeSearchBt.UseVisualStyleBackColor = true;
            this.peaCodeSearchBt.Click += new System.EventHandler(this.peaCodeSearchBt_Click);
            // 
            // agentSearchText
            // 
            this.agentSearchText.Location = new System.Drawing.Point(159, 24);
            this.agentSearchText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentSearchText.Mask = "00000000";
            this.agentSearchText.Name = "agentSearchText";
            this.agentSearchText.Size = new System.Drawing.Size(206, 23);
            this.agentSearchText.TabIndex = 8;
            this.agentSearchText.KeyDown += new System.Windows.Forms.KeyEventHandler(this.agentSearchText_KeyDown);
            // 
            // agentSearchBt
            // 
            this.agentSearchBt.Image = ((System.Drawing.Image)(resources.GetObject("agentSearchBt.Image")));
            this.agentSearchBt.Location = new System.Drawing.Point(19, 21);
            this.agentSearchBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentSearchBt.Name = "agentSearchBt";
            this.agentSearchBt.Size = new System.Drawing.Size(134, 28);
            this.agentSearchBt.TabIndex = 9;
            this.agentSearchBt.Text = "ค้นหาด้วยตัวแทน";
            this.agentSearchBt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.agentSearchBt.UseVisualStyleBackColor = true;
            this.agentSearchBt.Click += new System.EventHandler(this.agentSearchBt_Click);
            // 
            // portionSearchGridView
            // 
            this.portionSearchGridView.AllowUserToAddRows = false;
            this.portionSearchGridView.AllowUserToResizeRows = false;
            this.portionSearchGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.portionSearchGridView.BackgroundColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(211, 117, 191);
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.portionSearchGridView.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.portionSearchGridView.ColumnHeadersHeight = 22;
            this.portionSearchGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.portionSearchGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.CheckMark,
            this.AdvPayment,
            this.BranchId,
            this.LineId,
            this.NumberOfUser,
            this.PortionDesc,
            this.AgentLongName,
            this.AgencyHelp,
            this.validFrom,
            this.validTo,
            this.AgentId,
            this.TravelHelp});
            this.portionSearchGridView.EnableHeadersVisualStyles = false;
            this.portionSearchGridView.Location = new System.Drawing.Point(12, 58);
            this.portionSearchGridView.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.portionSearchGridView.Name = "portionSearchGridView";
            dataGridViewCellStyle10.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.Gold;
            dataGridViewCellStyle10.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            dataGridViewCellStyle10.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle10.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle10.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle10.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.portionSearchGridView.RowHeadersDefaultCellStyle = dataGridViewCellStyle10;
            this.portionSearchGridView.RowHeadersVisible = false;
            this.portionSearchGridView.RowHeadersWidth = 15;
            this.portionSearchGridView.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.portionSearchGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.portionSearchGridView.Size = new System.Drawing.Size(962, 289);
            this.portionSearchGridView.TabIndex = 13;
            this.portionSearchGridView.TabStop = false;
            this.portionSearchGridView.CellValueChanged += new System.Windows.Forms.DataGridViewCellEventHandler(this.portionSearchGridView_CellValueChanged);
            this.portionSearchGridView.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.portionSearchGridView_CellDoubleClick);
            this.portionSearchGridView.CellFormatting += new System.Windows.Forms.DataGridViewCellFormattingEventHandler(this.portionSearchGridView_CellFormatting);
            this.portionSearchGridView.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.portionSearchGridView_CellClick);
            this.portionSearchGridView.KeyDown += new System.Windows.Forms.KeyEventHandler(this.portionSearchGridView_KeyDown);
            // 
            // agentAssignmentGBox
            // 
            this.agentAssignmentGBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.agentAssignmentGBox.Controls.Add(this.agentStatusText);
            this.agentAssignmentGBox.Controls.Add(this.agentSearchText);
            this.agentAssignmentGBox.Controls.Add(this.agentStatusLabel);
            this.agentAssignmentGBox.Controls.Add(this.label1);
            this.agentAssignmentGBox.Controls.Add(this.agentType);
            this.agentAssignmentGBox.Controls.Add(this.agentSearchBt);
            this.agentAssignmentGBox.Controls.Add(this.agentNameLabel);
            this.agentAssignmentGBox.Controls.Add(this.label4);
            this.agentAssignmentGBox.Controls.Add(this.depositLabel);
            this.agentAssignmentGBox.Controls.Add(this.depositText);
            this.agentAssignmentGBox.Controls.Add(this.agentAddressText);
            this.agentAssignmentGBox.Controls.Add(this.agentNameText);
            this.agentAssignmentGBox.Location = new System.Drawing.Point(19, 4);
            this.agentAssignmentGBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentAssignmentGBox.Name = "agentAssignmentGBox";
            this.agentAssignmentGBox.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentAssignmentGBox.Size = new System.Drawing.Size(984, 115);
            this.agentAssignmentGBox.TabIndex = 0;
            this.agentAssignmentGBox.TabStop = false;
            this.agentAssignmentGBox.Text = "กำหนดตัวแทนของสายการเก็บเงิน";
            // 
            // agentStatusText
            // 
            this.agentStatusText.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.agentStatusText.Location = new System.Drawing.Point(817, 53);
            this.agentStatusText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentStatusText.Name = "agentStatusText";
            this.agentStatusText.ReadOnly = true;
            this.agentStatusText.Size = new System.Drawing.Size(147, 23);
            this.agentStatusText.TabIndex = 21;
            this.agentStatusText.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // agentStatusLabel
            // 
            this.agentStatusLabel.AutoSize = true;
            this.agentStatusLabel.Location = new System.Drawing.Point(764, 56);
            this.agentStatusLabel.Name = "agentStatusLabel";
            this.agentStatusLabel.Size = new System.Drawing.Size(53, 16);
            this.agentStatusLabel.TabIndex = 31;
            this.agentStatusLabel.Text = "สถานะ :";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(73, 56);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(80, 16);
            this.label1.TabIndex = 30;
            this.label1.Text = "ชนิดตัวแทน :";
            // 
            // agentType
            // 
            this.agentType.Location = new System.Drawing.Point(159, 53);
            this.agentType.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentType.Name = "agentType";
            this.agentType.ReadOnly = true;
            this.agentType.Size = new System.Drawing.Size(206, 23);
            this.agentType.TabIndex = 22;
            // 
            // agentNameLabel
            // 
            this.agentNameLabel.AutoSize = true;
            this.agentNameLabel.Location = new System.Drawing.Point(382, 27);
            this.agentNameLabel.Name = "agentNameLabel";
            this.agentNameLabel.Size = new System.Drawing.Size(72, 16);
            this.agentNameLabel.TabIndex = 0;
            this.agentNameLabel.Text = "ชื่อตัวแทน :";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(67, 86);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(81, 16);
            this.label4.TabIndex = 0;
            this.label4.Text = "ที่อยู่ตัวแทน :";
            // 
            // depositLabel
            // 
            this.depositLabel.AutoSize = true;
            this.depositLabel.Location = new System.Drawing.Point(382, 56);
            this.depositLabel.Name = "depositLabel";
            this.depositLabel.Size = new System.Drawing.Size(153, 16);
            this.depositLabel.TabIndex = 17;
            this.depositLabel.Text = "มูลค่าหลักทรัพย์ค้ำประกัน :";
            // 
            // depositText
            // 
            this.depositText.Location = new System.Drawing.Point(553, 53);
            this.depositText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.depositText.Name = "depositText";
            this.depositText.ReadOnly = true;
            this.depositText.Size = new System.Drawing.Size(188, 23);
            this.depositText.TabIndex = 23;
            this.depositText.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // agentAddressText
            // 
            this.agentAddressText.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.agentAddressText.Location = new System.Drawing.Point(159, 84);
            this.agentAddressText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentAddressText.Name = "agentAddressText";
            this.agentAddressText.ReadOnly = true;
            this.agentAddressText.Size = new System.Drawing.Size(805, 23);
            this.agentAddressText.TabIndex = 24;
            // 
            // agentNameText
            // 
            this.agentNameText.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.agentNameText.Location = new System.Drawing.Point(460, 23);
            this.agentNameText.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.agentNameText.Name = "agentNameText";
            this.agentNameText.ReadOnly = true;
            this.agentNameText.Size = new System.Drawing.Size(504, 23);
            this.agentNameText.TabIndex = 20;
            this.agentNameText.TextChanged += new System.EventHandler(this.agentNameText_TextChanged);
            // 
            // pSearchResultGBox
            // 
            this.pSearchResultGBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.pSearchResultGBox.Controls.Add(this.panel1);
            this.pSearchResultGBox.Controls.Add(this.btnSelectAll);
            this.pSearchResultGBox.Controls.Add(this.btnCancelAll);
            this.pSearchResultGBox.Controls.Add(this.portionSearchGridView);
            this.pSearchResultGBox.Location = new System.Drawing.Point(19, 225);
            this.pSearchResultGBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.pSearchResultGBox.Name = "pSearchResultGBox";
            this.pSearchResultGBox.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.pSearchResultGBox.Size = new System.Drawing.Size(984, 421);
            this.pSearchResultGBox.TabIndex = 0;
            this.pSearchResultGBox.TabStop = false;
            this.pSearchResultGBox.Text = "รายการสายการเก็บเงิน";
            // 
            // panel1
            // 
            this.panel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.panel1.BackColor = System.Drawing.SystemColors.Control;
            this.panel1.Controls.Add(this.removeBt);
            this.panel1.Controls.Add(this.clearBt);
            this.panel1.Controls.Add(this.saveBt);
            this.panel1.Location = new System.Drawing.Point(6, 355);
            this.panel1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(968, 58);
            this.panel1.TabIndex = 11;
            // 
            // removeBt
            // 
            this.removeBt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.removeBt.Enabled = false;
            this.removeBt.Image = ((System.Drawing.Image)(resources.GetObject("removeBt.Image")));
            this.removeBt.Location = new System.Drawing.Point(642, 11);
            this.removeBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.removeBt.Name = "removeBt";
            this.removeBt.Size = new System.Drawing.Size(140, 30);
            this.removeBt.TabIndex = 11;
            this.removeBt.Text = "    ลบสาย";
            this.removeBt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.removeBt.UseVisualStyleBackColor = true;
            this.removeBt.Click += new System.EventHandler(this.removeBt_Click);
            // 
            // clearBt
            // 
            this.clearBt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.clearBt.Location = new System.Drawing.Point(789, 11);
            this.clearBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.clearBt.Name = "clearBt";
            this.clearBt.Size = new System.Drawing.Size(140, 30);
            this.clearBt.TabIndex = 12;
            this.clearBt.Text = "เริ่มป้อนใหม่";
            this.clearBt.TextImageRelation = System.Windows.Forms.TextImageRelation.TextBeforeImage;
            this.clearBt.UseVisualStyleBackColor = true;
            this.clearBt.Click += new System.EventHandler(this.clearBt_Click);
            // 
            // saveBt
            // 
            this.saveBt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.saveBt.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.saveBt.Enabled = false;
            this.saveBt.Image = ((System.Drawing.Image)(resources.GetObject("saveBt.Image")));
            this.saveBt.Location = new System.Drawing.Point(495, 11);
            this.saveBt.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.saveBt.Name = "saveBt";
            this.saveBt.Size = new System.Drawing.Size(140, 30);
            this.saveBt.TabIndex = 10;
            this.saveBt.Text = "      บันทึก";
            this.saveBt.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.saveBt.UseVisualStyleBackColor = true;
            this.saveBt.Click += new System.EventHandler(this.saveBt_Click);
            // 
            // btnSelectAll
            // 
            this.btnSelectAll.Enabled = false;
            this.btnSelectAll.Location = new System.Drawing.Point(129, 24);
            this.btnSelectAll.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnSelectAll.Name = "btnSelectAll";
            this.btnSelectAll.Size = new System.Drawing.Size(114, 28);
            this.btnSelectAll.TabIndex = 17;
            this.btnSelectAll.Text = "เลือกหมด";
            this.btnSelectAll.UseVisualStyleBackColor = true;
            this.btnSelectAll.Click += new System.EventHandler(this.btnSelectAll_Click);
            // 
            // btnCancelAll
            // 
            this.btnCancelAll.Enabled = false;
            this.btnCancelAll.Location = new System.Drawing.Point(12, 24);
            this.btnCancelAll.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnCancelAll.Name = "btnCancelAll";
            this.btnCancelAll.Size = new System.Drawing.Size(114, 28);
            this.btnCancelAll.TabIndex = 16;
            this.btnCancelAll.Text = "ยกเลิกการเลือก";
            this.btnCancelAll.UseVisualStyleBackColor = true;
            this.btnCancelAll.Click += new System.EventHandler(this.btnCancelAll_Click);
            // 
            // dataGridViewTextBoxColumn1
            // 
            this.dataGridViewTextBoxColumn1.DataPropertyName = "LineId";
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn1.DefaultCellStyle = dataGridViewCellStyle11;
            this.dataGridViewTextBoxColumn1.HeaderText = "รหัสสายการเก็บเงิน";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            this.dataGridViewTextBoxColumn1.Width = 120;
            // 
            // dataGridViewTextBoxColumn2
            // 
            this.dataGridViewTextBoxColumn2.DataPropertyName = "NumOfCustomer";
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle12;
            this.dataGridViewTextBoxColumn2.HeaderText = "จำนวนผู้ใช้ไฟฟ้าในสาย";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.ReadOnly = true;
            this.dataGridViewTextBoxColumn2.Width = 140;
            // 
            // dataGridViewTextBoxColumn3
            // 
            this.dataGridViewTextBoxColumn3.DataPropertyName = "AreaCode";
            dataGridViewCellStyle13.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle13;
            this.dataGridViewTextBoxColumn3.HeaderText = "พื้นที่รับผิดชอบ";
            this.dataGridViewTextBoxColumn3.Name = "dataGridViewTextBoxColumn3";
            this.dataGridViewTextBoxColumn3.ReadOnly = true;
            this.dataGridViewTextBoxColumn3.Visible = false;
            this.dataGridViewTextBoxColumn3.Width = 140;
            // 
            // dataGridViewTextBoxColumn4
            // 
            this.dataGridViewTextBoxColumn4.DataPropertyName = "ReceiptManCode";
            dataGridViewCellStyle14.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            this.dataGridViewTextBoxColumn4.DefaultCellStyle = dataGridViewCellStyle14;
            this.dataGridViewTextBoxColumn4.HeaderText = "พนง.คุมใบเสร็จ";
            this.dataGridViewTextBoxColumn4.Name = "dataGridViewTextBoxColumn4";
            this.dataGridViewTextBoxColumn4.ReadOnly = true;
            this.dataGridViewTextBoxColumn4.Visible = false;
            this.dataGridViewTextBoxColumn4.Width = 150;
            // 
            // dataGridViewTextBoxColumn5
            // 
            this.dataGridViewTextBoxColumn5.DataPropertyName = "AgentLongName";
            dataGridViewCellStyle15.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            this.dataGridViewTextBoxColumn5.DefaultCellStyle = dataGridViewCellStyle15;
            this.dataGridViewTextBoxColumn5.HeaderText = "ตัวแทนเก็บเงิน";
            this.dataGridViewTextBoxColumn5.Name = "dataGridViewTextBoxColumn5";
            this.dataGridViewTextBoxColumn5.ReadOnly = true;
            this.dataGridViewTextBoxColumn5.Width = 200;
            // 
            // dataGridViewTextBoxColumn6
            // 
            this.dataGridViewTextBoxColumn6.DataPropertyName = "Zone";
            dataGridViewCellStyle16.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn6.DefaultCellStyle = dataGridViewCellStyle16;
            this.dataGridViewTextBoxColumn6.HeaderText = "โซน";
            this.dataGridViewTextBoxColumn6.Name = "dataGridViewTextBoxColumn6";
            this.dataGridViewTextBoxColumn6.ReadOnly = true;
            this.dataGridViewTextBoxColumn6.Width = 80;
            // 
            // dataGridViewTextBoxColumn7
            // 
            this.dataGridViewTextBoxColumn7.DataPropertyName = "AgentId";
            dataGridViewCellStyle17.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn7.DefaultCellStyle = dataGridViewCellStyle17;
            this.dataGridViewTextBoxColumn7.HeaderText = "AgentId";
            this.dataGridViewTextBoxColumn7.Name = "dataGridViewTextBoxColumn7";
            this.dataGridViewTextBoxColumn7.ReadOnly = true;
            this.dataGridViewTextBoxColumn7.Visible = false;
            this.dataGridViewTextBoxColumn7.Width = 5;
            // 
            // dataGridViewTextBoxColumn8
            // 
            this.dataGridViewTextBoxColumn8.DataPropertyName = "AgentId";
            dataGridViewCellStyle18.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle18.Format = "N2";
            dataGridViewCellStyle18.NullValue = "0.00";
            this.dataGridViewTextBoxColumn8.DefaultCellStyle = dataGridViewCellStyle18;
            this.dataGridViewTextBoxColumn8.HeaderText = "AgentId";
            this.dataGridViewTextBoxColumn8.Name = "dataGridViewTextBoxColumn8";
            this.dataGridViewTextBoxColumn8.ReadOnly = true;
            this.dataGridViewTextBoxColumn8.Visible = false;
            this.dataGridViewTextBoxColumn8.Width = 5;
            // 
            // dataGridViewTextBoxColumn9
            // 
            this.dataGridViewTextBoxColumn9.DataPropertyName = "ExtraHelp";
            dataGridViewCellStyle19.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle19.NullValue = "0.00";
            this.dataGridViewTextBoxColumn9.DefaultCellStyle = dataGridViewCellStyle19;
            this.dataGridViewTextBoxColumn9.HeaderText = "เงินเพิ่มพิเศษ";
            this.dataGridViewTextBoxColumn9.Name = "dataGridViewTextBoxColumn9";
            this.dataGridViewTextBoxColumn9.ReadOnly = true;
            this.dataGridViewTextBoxColumn9.Visible = false;
            this.dataGridViewTextBoxColumn9.Width = 80;
            // 
            // dataGridViewTextBoxColumn10
            // 
            this.dataGridViewTextBoxColumn10.DataPropertyName = "FarLandHelp";
            dataGridViewCellStyle20.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle20.Format = "N2";
            dataGridViewCellStyle20.NullValue = "0.00";
            this.dataGridViewTextBoxColumn10.DefaultCellStyle = dataGridViewCellStyle20;
            this.dataGridViewTextBoxColumn10.HeaderText = "พื้นที่ทุรกันดาน";
            this.dataGridViewTextBoxColumn10.Name = "dataGridViewTextBoxColumn10";
            this.dataGridViewTextBoxColumn10.Visible = false;
            this.dataGridViewTextBoxColumn10.Width = 80;
            // 
            // dataGridViewTextBoxColumn11
            // 
            this.dataGridViewTextBoxColumn11.DataPropertyName = "ValidFromText";
            dataGridViewCellStyle21.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.dataGridViewTextBoxColumn11.DefaultCellStyle = dataGridViewCellStyle21;
            this.dataGridViewTextBoxColumn11.HeaderText = "เริ่มต้น";
            this.dataGridViewTextBoxColumn11.Name = "dataGridViewTextBoxColumn11";
            // 
            // dataGridViewTextBoxColumn12
            // 
            this.dataGridViewTextBoxColumn12.DataPropertyName = "ValidToText";
            this.dataGridViewTextBoxColumn12.HeaderText = "สิ้นสุด";
            this.dataGridViewTextBoxColumn12.Name = "dataGridViewTextBoxColumn12";
            this.dataGridViewTextBoxColumn12.ReadOnly = true;
            this.dataGridViewTextBoxColumn12.Visible = false;
            this.dataGridViewTextBoxColumn12.Width = 5;
            // 
            // dataGridViewTextBoxColumn13
            // 
            this.dataGridViewTextBoxColumn13.DataPropertyName = "AgentId";
            this.dataGridViewTextBoxColumn13.HeaderText = "AgentId";
            this.dataGridViewTextBoxColumn13.Name = "dataGridViewTextBoxColumn13";
            this.dataGridViewTextBoxColumn13.ReadOnly = true;
            this.dataGridViewTextBoxColumn13.Visible = false;
            this.dataGridViewTextBoxColumn13.Width = 5;
            // 
            // CheckMark
            // 
            this.CheckMark.HeaderText = "ลบ";
            this.CheckMark.Name = "CheckMark";
            this.CheckMark.ToolTipText = "เลือกเพื่อนำออก";
            this.CheckMark.Width = 30;
            // 
            // AdvPayment
            // 
            this.AdvPayment.DataPropertyName = "AdvPayment";
            this.AdvPayment.HeaderText = "นำส่ง 30%";
            this.AdvPayment.Name = "AdvPayment";
            this.AdvPayment.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.AdvPayment.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            // 
            // BranchId
            // 
            this.BranchId.DataPropertyName = "BranchId";
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.BranchId.DefaultCellStyle = dataGridViewCellStyle2;
            this.BranchId.HeaderText = "การไฟฟ้า";
            this.BranchId.Name = "BranchId";
            this.BranchId.ReadOnly = true;
            // 
            // LineId
            // 
            this.LineId.DataPropertyName = "LineId";
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.LineId.DefaultCellStyle = dataGridViewCellStyle3;
            this.LineId.HeaderText = "รหัสสายการเก็บเงิน";
            this.LineId.Name = "LineId";
            this.LineId.ReadOnly = true;
            this.LineId.Width = 120;
            // 
            // NumberOfUser
            // 
            this.NumberOfUser.DataPropertyName = "NumOfCustomer";
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.Format = "N0";
            dataGridViewCellStyle4.NullValue = null;
            this.NumberOfUser.DefaultCellStyle = dataGridViewCellStyle4;
            this.NumberOfUser.HeaderText = "ผู้ใช้ไฟฟ้าในสาย";
            this.NumberOfUser.Name = "NumberOfUser";
            this.NumberOfUser.ReadOnly = true;
            this.NumberOfUser.Width = 110;
            // 
            // PortionDesc
            // 
            this.PortionDesc.DataPropertyName = "PortionDesc";
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.PortionDesc.DefaultCellStyle = dataGridViewCellStyle5;
            this.PortionDesc.HeaderText = "พื้นที่รับผิดชอบ";
            this.PortionDesc.Name = "PortionDesc";
            this.PortionDesc.ReadOnly = true;
            this.PortionDesc.Visible = false;
            // 
            // AgentLongName
            // 
            this.AgentLongName.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.AgentLongName.DataPropertyName = "AgentLongName";
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            this.AgentLongName.DefaultCellStyle = dataGridViewCellStyle6;
            this.AgentLongName.HeaderText = "ตัวแทนเก็บเงินเดิม";
            this.AgentLongName.Name = "AgentLongName";
            this.AgentLongName.ReadOnly = true;
            // 
            // AgencyHelp
            // 
            this.AgencyHelp.DataPropertyName = "AgencyHelp";
            dataGridViewCellStyle7.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            this.AgencyHelp.DefaultCellStyle = dataGridViewCellStyle7;
            this.AgencyHelp.HeaderText = "ประเภทเงินช่วยเหลือ";
            this.AgencyHelp.Name = "AgencyHelp";
            this.AgencyHelp.ReadOnly = true;
            this.AgencyHelp.Width = 250;
            // 
            // validFrom
            // 
            this.validFrom.DataPropertyName = "ValidFromText";
            dataGridViewCellStyle8.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.validFrom.DefaultCellStyle = dataGridViewCellStyle8;
            this.validFrom.HeaderText = "เริ่มต้น";
            this.validFrom.Name = "validFrom";
            this.validFrom.Visible = false;
            // 
            // validTo
            // 
            this.validTo.DataPropertyName = "ValidToText";
            dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            this.validTo.DefaultCellStyle = dataGridViewCellStyle9;
            this.validTo.HeaderText = "สิ้นสุด";
            this.validTo.Name = "validTo";
            this.validTo.Visible = false;
            // 
            // AgentId
            // 
            this.AgentId.DataPropertyName = "AgentId";
            this.AgentId.HeaderText = "AgentId";
            this.AgentId.Name = "AgentId";
            this.AgentId.ReadOnly = true;
            this.AgentId.Visible = false;
            this.AgentId.Width = 5;
            // 
            // TravelHelp
            // 
            this.TravelHelp.HeaderText = "TravelHelp";
            this.TravelHelp.Name = "TravelHelp";
            this.TravelHelp.Visible = false;
            // 
            // AgentPlanningSearchView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(1024, 650);
            this.Controls.Add(this.pSearchResultGBox);
            this.Controls.Add(this.agentAssignmentGBox);
            this.Controls.Add(this.portionSearchGroupBox);
            this.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.MinimumSize = new System.Drawing.Size(1024, 650);
            this.Name = "AgentPlanningSearchView";
            this.Size = new System.Drawing.Size(1024, 650);
            this.portionSearchGroupBox.ResumeLayout(false);
            this.portionSearchGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.portionSearchImgHint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.peaCodeImgHint)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.portionSearchGridView)).EndInit();
            this.agentAssignmentGBox.ResumeLayout(false);
            this.agentAssignmentGBox.PerformLayout();
            this.pSearchResultGBox.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox portionSearchGroupBox;
        private System.Windows.Forms.DataGridView portionSearchGridView;
        private System.Windows.Forms.PictureBox peaCodeImgHint;
        private System.Windows.Forms.PictureBox portionSearchImgHint;
        private System.Windows.Forms.GroupBox agentAssignmentGBox;
        private System.Windows.Forms.TextBox depositText;
        private System.Windows.Forms.TextBox agentAddressText;
        private System.Windows.Forms.TextBox agentNameText;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label depositLabel;
        private System.Windows.Forms.Button peaCodeSearchBt;
        private System.Windows.Forms.Button portionSearchBt;
        private System.Windows.Forms.Button agentSearchBt;
        private System.Windows.Forms.Label agentNameLabel;
        private System.Windows.Forms.GroupBox pSearchResultGBox;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Button clearBt;
        private System.Windows.Forms.Button saveBt;
        private System.Windows.Forms.MaskedTextBox agentSearchText;
        private System.Windows.Forms.MaskedTextBox lineCodeText;
        private System.Windows.Forms.MaskedTextBox peaCodeText;
        private System.Windows.Forms.TextBox agentStatusText;
        private System.Windows.Forms.Label agentStatusLabel;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox agentType;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox peaNameText;
        private System.Windows.Forms.Button removeBt;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn5;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn6;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn7;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn8;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn9;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn10;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn11;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn12;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn13;
        private System.Windows.Forms.Button btnSelectAll;
        private System.Windows.Forms.Button btnCancelAll;
        private System.Windows.Forms.DataGridViewCheckBoxColumn CheckMark;
        private System.Windows.Forms.DataGridViewCheckBoxColumn AdvPayment;
        private System.Windows.Forms.DataGridViewTextBoxColumn BranchId;
        private System.Windows.Forms.DataGridViewTextBoxColumn LineId;
        private System.Windows.Forms.DataGridViewTextBoxColumn NumberOfUser;
        private System.Windows.Forms.DataGridViewTextBoxColumn PortionDesc;
        private System.Windows.Forms.DataGridViewTextBoxColumn AgentLongName;
        private System.Windows.Forms.DataGridViewTextBoxColumn AgencyHelp;
        private System.Windows.Forms.DataGridViewTextBoxColumn validFrom;
        private System.Windows.Forms.DataGridViewTextBoxColumn validTo;
        private System.Windows.Forms.DataGridViewTextBoxColumn AgentId;
        private System.Windows.Forms.DataGridViewTextBoxColumn TravelHelp;
    }
}

