
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.ToolModule
{
    partial class RemarkListView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.ToolModule.RemarkListViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.panel2 = new System.Windows.Forms.Panel();
            this.deleteRemarkButton = new System.Windows.Forms.Button();
            this.addRemarkButton = new System.Windows.Forms.Button();
            this.editRemarkButton = new System.Windows.Forms.Button();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.remarkDataGridView = new System.Windows.Forms.DataGridView();
            this.GCheck = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.FncId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Description = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.fncDescTextBox = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.fncIdTextBox = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.groupBox1.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.remarkDataGridView)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tabControl1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(755, 449);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.tabControl1.Location = new System.Drawing.Point(3, 16);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(749, 430);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.panel2);
            this.tabPage1.Controls.Add(this.groupBox2);
            this.tabPage1.Controls.Add(this.groupBox3);
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(741, 401);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "จัดการ Remark";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.deleteRemarkButton);
            this.panel2.Controls.Add(this.addRemarkButton);
            this.panel2.Controls.Add(this.editRemarkButton);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(3, 363);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(735, 35);
            this.panel2.TabIndex = 5;
            // 
            // deleteRemarkButton
            // 
            this.deleteRemarkButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.deleteRemarkButton.Location = new System.Drawing.Point(599, 6);
            this.deleteRemarkButton.Name = "deleteRemarkButton";
            this.deleteRemarkButton.Size = new System.Drawing.Size(126, 23);
            this.deleteRemarkButton.TabIndex = 2;
            this.deleteRemarkButton.Text = "ลบ Remark ที่เลือก";
            this.deleteRemarkButton.UseVisualStyleBackColor = false;
            this.deleteRemarkButton.Click += new System.EventHandler(this.deleteRemarkButton_Click);
            // 
            // addRemarkButton
            // 
            this.addRemarkButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.addRemarkButton.Location = new System.Drawing.Point(365, 6);
            this.addRemarkButton.Name = "addRemarkButton";
            this.addRemarkButton.Size = new System.Drawing.Size(111, 23);
            this.addRemarkButton.TabIndex = 1;
            this.addRemarkButton.Text = "เพิ่ม Remark";
            this.addRemarkButton.UseVisualStyleBackColor = false;
            this.addRemarkButton.Click += new System.EventHandler(this.addRemarkButton_Click);
            // 
            // editRemarkButton
            // 
            this.editRemarkButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.editRemarkButton.Location = new System.Drawing.Point(482, 6);
            this.editRemarkButton.Name = "editRemarkButton";
            this.editRemarkButton.Size = new System.Drawing.Size(111, 23);
            this.editRemarkButton.TabIndex = 0;
            this.editRemarkButton.Text = "แก้ไข Remak";
            this.editRemarkButton.UseVisualStyleBackColor = false;
            this.editRemarkButton.Click += new System.EventHandler(this.editRemarkButton_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.remarkDataGridView);
            this.groupBox2.Location = new System.Drawing.Point(10, 97);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Padding = new System.Windows.Forms.Padding(5);
            this.groupBox2.Size = new System.Drawing.Size(718, 256);
            this.groupBox2.TabIndex = 6;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "รายละเอียด Remark";
            // 
            // remarkDataGridView
            // 
            this.remarkDataGridView.AllowUserToAddRows = false;
            this.remarkDataGridView.AllowUserToDeleteRows = false;
            this.remarkDataGridView.AllowUserToOrderColumns = true;
            this.remarkDataGridView.AllowUserToResizeRows = false;
            this.remarkDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.remarkDataGridView.BackgroundColor = System.Drawing.SystemColors.Window;
            this.remarkDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.remarkDataGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.GCheck,
            this.FncId,
            this.Description});
            this.remarkDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.remarkDataGridView.GridColor = System.Drawing.SystemColors.Control;
            this.remarkDataGridView.Location = new System.Drawing.Point(5, 21);
            this.remarkDataGridView.Name = "remarkDataGridView";
            this.remarkDataGridView.RowHeadersVisible = false;
            this.remarkDataGridView.RowTemplate.Height = 25;
            this.remarkDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.remarkDataGridView.Size = new System.Drawing.Size(708, 230);
            this.remarkDataGridView.TabIndex = 1;
            // 
            // GCheck
            // 
            this.GCheck.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.GCheck.DataPropertyName = "GCheck";
            this.GCheck.FillWeight = 1F;
            this.GCheck.HeaderText = "เลือก";
            this.GCheck.MinimumWidth = 40;
            this.GCheck.Name = "GCheck";
            this.GCheck.Width = 42;
            // 
            // FncId
            // 
            this.FncId.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.FncId.DataPropertyName = "FncId";
            this.FncId.FillWeight = 1F;
            this.FncId.HeaderText = "รหัสฟังก์ชัน";
            this.FncId.MinimumWidth = 120;
            this.FncId.Name = "FncId";
            this.FncId.ReadOnly = true;
            this.FncId.Visible = false;
            // 
            // Description
            // 
            this.Description.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.Description.DataPropertyName = "Description";
            this.Description.FillWeight = 1F;
            this.Description.HeaderText = "Remark";
            this.Description.MinimumWidth = 200;
            this.Description.Name = "Description";
            this.Description.ReadOnly = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox3.Controls.Add(this.fncDescTextBox);
            this.groupBox3.Controls.Add(this.label2);
            this.groupBox3.Controls.Add(this.fncIdTextBox);
            this.groupBox3.Controls.Add(this.label1);
            this.groupBox3.Location = new System.Drawing.Point(10, 8);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(718, 83);
            this.groupBox3.TabIndex = 4;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "ฟังก์ชัน";
            // 
            // fncDescTextBox
            // 
            this.fncDescTextBox.Location = new System.Drawing.Point(103, 50);
            this.fncDescTextBox.Name = "fncDescTextBox";
            this.fncDescTextBox.ReadOnly = true;
            this.fncDescTextBox.Size = new System.Drawing.Size(609, 23);
            this.fncDescTextBox.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(23, 53);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(70, 16);
            this.label2.TabIndex = 2;
            this.label2.Text = "รายละเอียด";
            // 
            // fncIdTextBox
            // 
            this.fncIdTextBox.Location = new System.Drawing.Point(103, 24);
            this.fncIdTextBox.Name = "fncIdTextBox";
            this.fncIdTextBox.ReadOnly = true;
            this.fncIdTextBox.Size = new System.Drawing.Size(233, 23);
            this.fncIdTextBox.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(24, 27);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(69, 16);
            this.label1.TabIndex = 0;
            this.label1.Text = "รหัสฟังก์ชัน";
            // 
            // RemarkListView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.groupBox1);
            this.Name = "RemarkListView";
            this.Size = new System.Drawing.Size(755, 449);
            this.groupBox1.ResumeLayout(false);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.remarkDataGridView)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.DataGridView remarkDataGridView;
        private System.Windows.Forms.DataGridViewCheckBoxColumn GCheck;
        private System.Windows.Forms.DataGridViewTextBoxColumn FncId;
        private System.Windows.Forms.DataGridViewTextBoxColumn Description;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Button deleteRemarkButton;
        private System.Windows.Forms.Button addRemarkButton;
        private System.Windows.Forms.Button editRemarkButton;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.TextBox fncDescTextBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox fncIdTextBox;
        private System.Windows.Forms.Label label1;



    }
}

