
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.ToolModule
{
    partial class QueueSetupView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.ToolModule.QueueSetupViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.printerTab = new System.Windows.Forms.TabControl();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.usbRdoBt = new System.Windows.Forms.RadioButton();
            this.com2RdoBt = new System.Windows.Forms.RadioButton();
            this.com1RdoBt = new System.Windows.Forms.RadioButton();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.button1 = new System.Windows.Forms.Button();
            this.qFilePathMskTxtBox = new System.Windows.Forms.MaskedTextBox();
            this.cancelButton = new System.Windows.Forms.Button();
            this.saveButton = new System.Windows.Forms.Button();
            this.panel2 = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.qEnablecheckbox = new System.Windows.Forms.CheckBox();
            this.panel1.SuspendLayout();
            this.panel3.SuspendLayout();
            this.printerTab.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.panel3);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(10, 10);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(582, 570);
            this.panel1.TabIndex = 1;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.printerTab);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Padding = new System.Windows.Forms.Padding(5);
            this.panel3.Size = new System.Drawing.Size(582, 537);
            this.panel3.TabIndex = 1;
            // 
            // printerTab
            // 
            this.printerTab.Controls.Add(this.tabPage2);
            this.printerTab.Dock = System.Windows.Forms.DockStyle.Fill;
            this.printerTab.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.printerTab.Location = new System.Drawing.Point(5, 5);
            this.printerTab.Name = "printerTab";
            this.printerTab.SelectedIndex = 0;
            this.printerTab.Size = new System.Drawing.Size(572, 527);
            this.printerTab.TabIndex = 0;
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.groupBox2);
            this.tabPage2.Controls.Add(this.groupBox1);
            this.tabPage2.Controls.Add(this.groupBox4);
            this.tabPage2.Controls.Add(this.cancelButton);
            this.tabPage2.Controls.Add(this.saveButton);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(564, 501);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "กำหนดค่าสำหรับ POS";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.usbRdoBt);
            this.groupBox1.Controls.Add(this.com2RdoBt);
            this.groupBox1.Controls.Add(this.com1RdoBt);
            this.groupBox1.Location = new System.Drawing.Point(6, 131);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(552, 53);
            this.groupBox1.TabIndex = 38;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "ระบุประเภทการเชื่อมต่อของ Barcode Scanner";
            // 
            // usbRdoBt
            // 
            this.usbRdoBt.AutoSize = true;
            this.usbRdoBt.Location = new System.Drawing.Point(277, 21);
            this.usbRdoBt.Name = "usbRdoBt";
            this.usbRdoBt.Size = new System.Drawing.Size(73, 17);
            this.usbRdoBt.TabIndex = 2;
            this.usbRdoBt.Text = "พอร์ต USB";
            this.usbRdoBt.UseVisualStyleBackColor = true;
            this.usbRdoBt.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.usbRdoBt_KeyPress);
            // 
            // com2RdoBt
            // 
            this.com2RdoBt.AutoSize = true;
            this.com2RdoBt.Location = new System.Drawing.Point(150, 21);
            this.com2RdoBt.Name = "com2RdoBt";
            this.com2RdoBt.Size = new System.Drawing.Size(83, 17);
            this.com2RdoBt.TabIndex = 1;
            this.com2RdoBt.Text = "พอร์ต COM2";
            this.com2RdoBt.UseVisualStyleBackColor = true;
            this.com2RdoBt.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.com2RdoBt_KeyPress);
            // 
            // com1RdoBt
            // 
            this.com1RdoBt.AutoSize = true;
            this.com1RdoBt.Checked = true;
            this.com1RdoBt.Location = new System.Drawing.Point(26, 21);
            this.com1RdoBt.Name = "com1RdoBt";
            this.com1RdoBt.Size = new System.Drawing.Size(83, 17);
            this.com1RdoBt.TabIndex = 0;
            this.com1RdoBt.TabStop = true;
            this.com1RdoBt.Text = "พอร์ต COM1";
            this.com1RdoBt.UseVisualStyleBackColor = true;
            this.com1RdoBt.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.com1RdoBt_KeyPress);
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox4.Controls.Add(this.button1);
            this.groupBox4.Controls.Add(this.qFilePathMskTxtBox);
            this.groupBox4.Location = new System.Drawing.Point(6, 72);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(552, 53);
            this.groupBox4.TabIndex = 37;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "ระบุ Path ของไฟล์สำหรับระบบจัดการคิว";
            // 
            // button1
            // 
            this.button1.Enabled = false;
            this.button1.Location = new System.Drawing.Point(508, 18);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(32, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "...";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // qFilePathMskTxtBox
            // 
            this.qFilePathMskTxtBox.Location = new System.Drawing.Point(16, 19);
            this.qFilePathMskTxtBox.Name = "qFilePathMskTxtBox";
            this.qFilePathMskTxtBox.ReadOnly = true;
            this.qFilePathMskTxtBox.Size = new System.Drawing.Size(489, 21);
            this.qFilePathMskTxtBox.TabIndex = 0;
            this.qFilePathMskTxtBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.qFilePathMskTxtBox_KeyPress);
            // 
            // cancelButton
            // 
            this.cancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.cancelButton.Location = new System.Drawing.Point(485, 190);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(75, 23);
            this.cancelButton.TabIndex = 5;
            this.cancelButton.Text = "ยกเลิก";
            this.cancelButton.UseVisualStyleBackColor = false;
            this.cancelButton.Click += new System.EventHandler(this.cancelButton_Click);
            // 
            // saveButton
            // 
            this.saveButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.saveButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.saveButton.Location = new System.Drawing.Point(402, 190);
            this.saveButton.Name = "saveButton";
            this.saveButton.Size = new System.Drawing.Size(75, 23);
            this.saveButton.TabIndex = 4;
            this.saveButton.Text = "ตกลง";
            this.saveButton.UseVisualStyleBackColor = false;
            this.saveButton.Click += new System.EventHandler(this.saveButton_Click);
            // 
            // panel2
            // 
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(0, 537);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(582, 33);
            this.panel2.TabIndex = 0;
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.qEnablecheckbox);
            this.groupBox2.Location = new System.Drawing.Point(6, 19);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(552, 53);
            this.groupBox2.TabIndex = 39;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "การจัดการระบบคิว";
            // 
            // qEnablecheckbox
            // 
            this.qEnablecheckbox.AutoSize = true;
            this.qEnablecheckbox.Location = new System.Drawing.Point(16, 21);
            this.qEnablecheckbox.Name = "qEnablecheckbox";
            this.qEnablecheckbox.Size = new System.Drawing.Size(126, 17);
            this.qEnablecheckbox.TabIndex = 0;
            this.qEnablecheckbox.Text = "เปิดการใช้งานระบบคิว";
            this.qEnablecheckbox.UseVisualStyleBackColor = true;
            // 
            // QueueSetupView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(211, 117, 191);
            this.Controls.Add(this.panel1);
            this.Name = "QueueSetupView";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.Size = new System.Drawing.Size(602, 590);
            this.panel1.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.printerTab.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.TabControl printerTab;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button saveButton;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.MaskedTextBox qFilePathMskTxtBox;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton usbRdoBt;
        private System.Windows.Forms.RadioButton com2RdoBt;
        private System.Windows.Forms.RadioButton com1RdoBt;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.CheckBox qEnablecheckbox;
    }
}

