//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// This interface defines the contract between the Presenter and its View, following the
// Model-View-Presenter pattern. 
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using PEA.BPM.BillPrintingModule.Interface.BusinessEntities;
using System.Collections.Generic;
namespace PEA.BPM.BillPrintingModule
{
    public interface IBillProcessingListView
    {
        List<A4Bill> A4Bill { get; set;}
        List<GreenBill> GreenBill { get; set;}
        List<BlueBill> BlueBill { get; set;}
        List<PrintableId> PrintId { get; set;}
        List<Bills> BillTxt { get; set;}
        int? TmpBillType { get; set;}
        string TmpBillPeriod { get; set;}
        string ApproverId { get; set; }
        string ApproverName { get; set;}
        string ApproverPosition { get; set;}
        bool IsReprintBill { get; set;}
        int? A4Reprint { get; set; }
        int? HasOrgDoc { get; set; }
        int? PrintCondition { get; set; }
        //void LoadBillToListView();   
        void OnWaitCursor(bool set);
        void PrintSelectedBill();
        void ClearList();
        void SummarizeRecords();
        string[] GetPrinterCode();
        string GetOnPrintBillType();
    }
}

