
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.CashManagementModule
{
    partial class AdjustOpenBalanceView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.CashManagementModule.AdjustOpenBalanceViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel6 = new System.Windows.Forms.Panel();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.groupBox6 = new System.Windows.Forms.GroupBox();
            this.totalAmtTxt = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.openBalanceNetTxt = new System.Windows.Forms.TextBox();
            this.label19 = new System.Windows.Forms.Label();
            this.cancelAllButton = new System.Windows.Forms.Button();
            this.refNoTxt = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.flowCBox = new System.Windows.Forms.ComboBox();
            this.okButton = new System.Windows.Forms.Button();
            this.panel2 = new System.Windows.Forms.Panel();
            this.quiteBt = new System.Windows.Forms.Button();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.inputGb = new System.Windows.Forms.GroupBox();
            this.paymentTypeTabControl = new System.Windows.Forms.TabControl();
            this.cashTabPage = new System.Windows.Forms.TabPage();
            this.cashAmountTextBox = new PEA.BPM.Architecture.CommonUtilities.TextBoxDecimal();
            this.label13 = new System.Windows.Forms.Label();
            this.chequeTabPage = new System.Windows.Forms.TabPage();
            this.chqBankSearchButton = new System.Windows.Forms.Button();
            this.chequeBankComboBox = new System.Windows.Forms.ComboBox();
            this.chqAccNoTxt = new System.Windows.Forms.TextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.chqDtPicker = new System.Windows.Forms.DateTimePicker();
            this.label15 = new System.Windows.Forms.Label();
            this.chqNoTxt = new System.Windows.Forms.TextBox();
            this.label16 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.chequeActualAmountTextBox = new PEA.BPM.Architecture.CommonUtilities.TextBoxDecimal();
            this.panel7 = new System.Windows.Forms.Panel();
            this.editIcom = new System.Windows.Forms.PictureBox();
            this.cancelButton = new System.Windows.Forms.Button();
            this.addEditButton = new System.Windows.Forms.Button();
            this.paymentDataGridView = new System.Windows.Forms.DataGridView();
            this.methodNameDgColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Column6 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Amount = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.EditButton = new System.Windows.Forms.DataGridViewImageColumn();
            this.deleteButton = new System.Windows.Forms.DataGridViewImageColumn();
            this.BankKey = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ChqNo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ChqAccNo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ChqDt = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.PtId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.currentOpeningGb = new System.Windows.Forms.GroupBox();
            this.currentOpenGv = new System.Windows.Forms.DataGridView();
            this.FlowDesc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.CashAmtTxt = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.ChqAmtTxt = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.TotalAmt = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.panel3 = new System.Windows.Forms.Panel();
            this.branchIdMaskedTextBox = new System.Windows.Forms.MaskedTextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.cashierCBox = new System.Windows.Forms.ComboBox();
            this.panel9 = new System.Windows.Forms.Panel();
            this.panel6.SuspendLayout();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.panel2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.inputGb.SuspendLayout();
            this.paymentTypeTabControl.SuspendLayout();
            this.cashTabPage.SuspendLayout();
            this.chequeTabPage.SuspendLayout();
            this.panel7.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.editIcom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.paymentDataGridView)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.currentOpeningGb.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.currentOpenGv)).BeginInit();
            this.panel3.SuspendLayout();
            this.panel9.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(10, 10);
            this.panel1.Name = "panel1";
            this.panel1.Padding = new System.Windows.Forms.Padding(5);
            this.panel1.Size = new System.Drawing.Size(982, 568);
            this.panel1.TabIndex = 0;
            // 
            // panel6
            // 
            this.panel6.Controls.Add(this.splitContainer1);
            this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel6.Location = new System.Drawing.Point(3, 428);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(966, 75);
            this.panel6.TabIndex = 4;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.groupBox6);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.groupBox5);
            this.splitContainer1.Size = new System.Drawing.Size(966, 75);
            this.splitContainer1.SplitterDistance = 476;
            this.splitContainer1.TabIndex = 7;
            // 
            // groupBox6
            // 
            this.groupBox6.Controls.Add(this.totalAmtTxt);
            this.groupBox6.Controls.Add(this.label10);
            this.groupBox6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox6.Location = new System.Drawing.Point(0, 0);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Padding = new System.Windows.Forms.Padding(3, 3, 5, 10);
            this.groupBox6.Size = new System.Drawing.Size(476, 75);
            this.groupBox6.TabIndex = 7;
            this.groupBox6.TabStop = false;
            // 
            // totalAmtTxt
            // 
            this.totalAmtTxt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.totalAmtTxt.BackColor = System.Drawing.SystemColors.Window;
            this.totalAmtTxt.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F);
            this.totalAmtTxt.ForeColor = System.Drawing.Color.Red;
            this.totalAmtTxt.Location = new System.Drawing.Point(196, 16);
            this.totalAmtTxt.Name = "totalAmtTxt";
            this.totalAmtTxt.ReadOnly = true;
            this.totalAmtTxt.Size = new System.Drawing.Size(259, 44);
            this.totalAmtTxt.TabIndex = 2;
            this.totalAmtTxt.Text = "0.00";
            this.totalAmtTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // label10
            // 
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 21.75F);
            this.label10.ForeColor = System.Drawing.Color.Red;
            this.label10.Location = new System.Drawing.Point(24, 18);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(166, 38);
            this.label10.TabIndex = 3;
            this.label10.Text = "ยอดปรับปรุง";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.openBalanceNetTxt);
            this.groupBox5.Controls.Add(this.label19);
            this.groupBox5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox5.Location = new System.Drawing.Point(0, 0);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Padding = new System.Windows.Forms.Padding(3, 3, 5, 10);
            this.groupBox5.Size = new System.Drawing.Size(486, 75);
            this.groupBox5.TabIndex = 5;
            this.groupBox5.TabStop = false;
            // 
            // openBalanceNetTxt
            // 
            this.openBalanceNetTxt.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.openBalanceNetTxt.BackColor = System.Drawing.SystemColors.Window;
            this.openBalanceNetTxt.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.openBalanceNetTxt.ForeColor = System.Drawing.Color.Blue;
            this.openBalanceNetTxt.Location = new System.Drawing.Point(190, 16);
            this.openBalanceNetTxt.Name = "openBalanceNetTxt";
            this.openBalanceNetTxt.ReadOnly = true;
            this.openBalanceNetTxt.Size = new System.Drawing.Size(269, 44);
            this.openBalanceNetTxt.TabIndex = 4;
            this.openBalanceNetTxt.Text = "0.00";
            this.openBalanceNetTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // label19
            // 
            this.label19.Font = new System.Drawing.Font("Microsoft Sans Serif", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.label19.ForeColor = System.Drawing.Color.Blue;
            this.label19.Location = new System.Drawing.Point(6, 13);
            this.label19.Name = "label19";
            this.label19.Size = new System.Drawing.Size(178, 48);
            this.label19.TabIndex = 5;
            this.label19.Text = "ยอดยกมาสุทธิ";
            this.label19.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cancelAllButton
            // 
            this.cancelAllButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelAllButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.cancelAllButton.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.cancelAllButton.Location = new System.Drawing.Point(755, 8);
            this.cancelAllButton.Name = "cancelAllButton";
            this.cancelAllButton.Size = new System.Drawing.Size(100, 36);
            this.cancelAllButton.TabIndex = 4;
            this.cancelAllButton.Text = "ล้างค่า";
            this.cancelAllButton.UseVisualStyleBackColor = false;
            this.cancelAllButton.Click += new System.EventHandler(this.cancelAllButton_Click);
            // 
            // refNoTxt
            // 
            this.refNoTxt.Location = new System.Drawing.Point(554, 19);
            this.refNoTxt.MaxLength = 18;
            this.refNoTxt.Name = "refNoTxt";
            this.refNoTxt.Size = new System.Drawing.Size(318, 22);
            this.refNoTxt.TabIndex = 36;
            this.refNoTxt.KeyDown += new System.Windows.Forms.KeyEventHandler(this.refNoTxt_KeyDown);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(409, 22);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(139, 14);
            this.label4.TabIndex = 35;
            this.label4.Text = "เลขที่อ้างอิง (18 ตัวอักษร)";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(14, 22);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(85, 14);
            this.label2.TabIndex = 34;
            this.label2.Text = "รายการปรับยอด";
            // 
            // flowCBox
            // 
            this.flowCBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.flowCBox.FormattingEnabled = true;
            this.flowCBox.Items.AddRange(new object[] {
            "----------------- เลือกรายการ -----------------",
            "----- เพิ่มยอดยกมา (+) -----",
            "ปรับเพิ่มยอดนำเงินเข้าระบบ",
            "ปรับเพิ่มยอดรับจากระบบรับชำระเงิน",
            "ปรับลดยอดนำฝากธนาคาร",
            "ปรับลดยอดจ่ายเงินตามใบสำคัญจ่าย",
            "----- ลดยอดยกมา (-) ------",
            "ปรับลดยอดนำเงินเข้าระบบ",
            "ปรับลดยอดรับจากระบบรับชำระเงิน",
            "ปรับเพิ่มยอดนำฝากธนาคาร",
            "ปรับเพิ่มยอดจ่ายเงินตามใบสำคัญจ่าย"});
            this.flowCBox.Location = new System.Drawing.Point(103, 19);
            this.flowCBox.Name = "flowCBox";
            this.flowCBox.Size = new System.Drawing.Size(275, 22);
            this.flowCBox.TabIndex = 33;
            this.flowCBox.SelectedIndexChanged += new System.EventHandler(this.flowCBox_SelectedIndexChanged);
            // 
            // okButton
            // 
            this.okButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.okButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.okButton.Enabled = false;
            this.okButton.Font = new System.Drawing.Font("Tahoma", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.okButton.Location = new System.Drawing.Point(649, 8);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(100, 36);
            this.okButton.TabIndex = 3;
            this.okButton.Text = "บันทึก";
            this.okButton.UseVisualStyleBackColor = false;
            this.okButton.Click += new System.EventHandler(this.okButton_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.quiteBt);
            this.panel2.Controls.Add(this.cancelAllButton);
            this.panel2.Controls.Add(this.okButton);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(5, 511);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(972, 52);
            this.panel2.TabIndex = 0;
            // 
            // quiteBt
            // 
            this.quiteBt.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.quiteBt.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.quiteBt.Font = new System.Drawing.Font("Tahoma", 12F);
            this.quiteBt.Location = new System.Drawing.Point(861, 8);
            this.quiteBt.Name = "quiteBt";
            this.quiteBt.Size = new System.Drawing.Size(100, 36);
            this.quiteBt.TabIndex = 5;
            this.quiteBt.Text = "ออก";
            this.quiteBt.UseVisualStyleBackColor = false;
            this.quiteBt.Click += new System.EventHandler(this.quiteBt_Click);
            // 
            // groupBox3
            // 
            this.groupBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox3.Controls.Add(this.inputGb);
            this.groupBox3.Controls.Add(this.paymentDataGridView);
            this.groupBox3.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.Location = new System.Drawing.Point(3, 123);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(966, 305);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "รายการปรับปรุง";
            // 
            // inputGb
            // 
            this.inputGb.Controls.Add(this.paymentTypeTabControl);
            this.inputGb.Controls.Add(this.panel7);
            this.inputGb.Controls.Add(this.refNoTxt);
            this.inputGb.Controls.Add(this.flowCBox);
            this.inputGb.Controls.Add(this.label4);
            this.inputGb.Controls.Add(this.label2);
            this.inputGb.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.inputGb.Enabled = false;
            this.inputGb.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.inputGb.Location = new System.Drawing.Point(3, 128);
            this.inputGb.Name = "inputGb";
            this.inputGb.Size = new System.Drawing.Size(960, 174);
            this.inputGb.TabIndex = 1;
            this.inputGb.TabStop = false;
            this.inputGb.Text = "เพิ่ม/ลด ยอดยกมา";
            // 
            // paymentTypeTabControl
            // 
            this.paymentTypeTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.paymentTypeTabControl.Appearance = System.Windows.Forms.TabAppearance.Buttons;
            this.paymentTypeTabControl.Controls.Add(this.cashTabPage);
            this.paymentTypeTabControl.Controls.Add(this.chequeTabPage);
            this.paymentTypeTabControl.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.paymentTypeTabControl.Location = new System.Drawing.Point(3, 48);
            this.paymentTypeTabControl.Name = "paymentTypeTabControl";
            this.paymentTypeTabControl.SelectedIndex = 0;
            this.paymentTypeTabControl.Size = new System.Drawing.Size(954, 92);
            this.paymentTypeTabControl.TabIndex = 0;
            this.paymentTypeTabControl.SelectedIndexChanged += new System.EventHandler(this.paymentTypeTabControl_SelectedIndexChanged);
            // 
            // cashTabPage
            // 
            this.cashTabPage.BackColor = System.Drawing.Color.White;
            this.cashTabPage.Controls.Add(this.cashAmountTextBox);
            this.cashTabPage.Controls.Add(this.label13);
            this.cashTabPage.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.cashTabPage.Location = new System.Drawing.Point(4, 26);
            this.cashTabPage.Name = "cashTabPage";
            this.cashTabPage.Padding = new System.Windows.Forms.Padding(3);
            this.cashTabPage.Size = new System.Drawing.Size(946, 62);
            this.cashTabPage.TabIndex = 0;
            this.cashTabPage.Text = "เงินสด";
            this.cashTabPage.UseVisualStyleBackColor = true;
            // 
            // cashAmountTextBox
            // 
            this.cashAmountTextBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.cashAmountTextBox.Location = new System.Drawing.Point(133, 11);
            this.cashAmountTextBox.MaxLength = 16;
            this.cashAmountTextBox.MaxLengthDecimalPoint = 2;
            this.cashAmountTextBox.Name = "cashAmountTextBox";
            this.cashAmountTextBox.Size = new System.Drawing.Size(216, 38);
            this.cashAmountTextBox.TabIndex = 1;
            this.cashAmountTextBox.Text = "0.00";
            this.cashAmountTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.cashAmountTextBox.Click += new System.EventHandler(this.cashAmountTextBox_Click);
            this.cashAmountTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cashAmountTextBox_KeyDown);
            this.cashAmountTextBox.Leave += new System.EventHandler(this.cashAmountTextBox_Leave);
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.label13.Location = new System.Drawing.Point(15, 15);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(113, 29);
            this.label13.TabIndex = 0;
            this.label13.Text = "จำนวนเงิน";
            // 
            // chequeTabPage
            // 
            this.chequeTabPage.BackColor = System.Drawing.Color.White;
            this.chequeTabPage.Controls.Add(this.chqBankSearchButton);
            this.chequeTabPage.Controls.Add(this.chequeBankComboBox);
            this.chequeTabPage.Controls.Add(this.chqAccNoTxt);
            this.chequeTabPage.Controls.Add(this.label14);
            this.chequeTabPage.Controls.Add(this.chqDtPicker);
            this.chequeTabPage.Controls.Add(this.label15);
            this.chequeTabPage.Controls.Add(this.chqNoTxt);
            this.chequeTabPage.Controls.Add(this.label16);
            this.chequeTabPage.Controls.Add(this.label17);
            this.chequeTabPage.Controls.Add(this.label18);
            this.chequeTabPage.Controls.Add(this.chequeActualAmountTextBox);
            this.chequeTabPage.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.chequeTabPage.Location = new System.Drawing.Point(4, 26);
            this.chequeTabPage.Name = "chequeTabPage";
            this.chequeTabPage.Size = new System.Drawing.Size(946, 62);
            this.chequeTabPage.TabIndex = 3;
            this.chequeTabPage.Text = "เช็ค";
            this.chequeTabPage.UseVisualStyleBackColor = true;
            // 
            // chqBankSearchButton
            // 
            this.chqBankSearchButton.ImageAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.chqBankSearchButton.Location = new System.Drawing.Point(888, 5);
            this.chqBankSearchButton.Name = "chqBankSearchButton";
            this.chqBankSearchButton.Size = new System.Drawing.Size(26, 24);
            this.chqBankSearchButton.TabIndex = 4;
            this.chqBankSearchButton.Text = "...";
            this.chqBankSearchButton.UseVisualStyleBackColor = true;
            this.chqBankSearchButton.Click += new System.EventHandler(this.chqBankSearchButton_Click);
            this.chqBankSearchButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chqBankSearchButton_KeyDown);
            // 
            // chequeBankComboBox
            // 
            this.chequeBankComboBox.DisplayMember = "BankName";
            this.chequeBankComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.chequeBankComboBox.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.chequeBankComboBox.FormattingEnabled = true;
            this.chequeBankComboBox.Location = new System.Drawing.Point(494, 6);
            this.chequeBankComboBox.Name = "chequeBankComboBox";
            this.chequeBankComboBox.Size = new System.Drawing.Size(389, 22);
            this.chequeBankComboBox.TabIndex = 3;
            this.chequeBankComboBox.ValueMember = "BankKey";
            this.chequeBankComboBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chequeBankComboBox_KeyDown);
            // 
            // chqAccNoTxt
            // 
            this.chqAccNoTxt.Location = new System.Drawing.Point(104, 33);
            this.chqAccNoTxt.MaxLength = 18;
            this.chqAccNoTxt.Name = "chqAccNoTxt";
            this.chqAccNoTxt.Size = new System.Drawing.Size(100, 22);
            this.chqAccNoTxt.TabIndex = 7;
            this.chqAccNoTxt.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chqAccNoTxt_KeyDown);
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(21, 37);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(79, 14);
            this.label14.TabIndex = 2;
            this.label14.Text = "เลขที่บัญชีเช็ค";
            // 
            // chqDtPicker
            // 
            this.chqDtPicker.CalendarFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.chqDtPicker.CustomFormat = "dd/MM/yyyy";
            this.chqDtPicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.chqDtPicker.Location = new System.Drawing.Point(291, 33);
            this.chqDtPicker.Name = "chqDtPicker";
            this.chqDtPicker.Size = new System.Drawing.Size(115, 22);
            this.chqDtPicker.TabIndex = 8;
            this.chqDtPicker.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chqDtPicker_KeyDown);
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Font = new System.Drawing.Font("Tahoma", 9F);
            this.label15.Location = new System.Drawing.Point(237, 37);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(48, 14);
            this.label15.TabIndex = 9;
            this.label15.Text = "วันที่เช็ค";
            // 
            // chqNoTxt
            // 
            this.chqNoTxt.Location = new System.Drawing.Point(291, 5);
            this.chqNoTxt.MaxLength = 17;
            this.chqNoTxt.Name = "chqNoTxt";
            this.chqNoTxt.Size = new System.Drawing.Size(115, 22);
            this.chqNoTxt.TabIndex = 2;
            this.chqNoTxt.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chqNoTxt_KeyDown);
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Font = new System.Drawing.Font("Tahoma", 9F);
            this.label16.Location = new System.Drawing.Point(232, 9);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(53, 14);
            this.label16.TabIndex = 2;
            this.label16.Text = "เลขที่เช็ค";
            // 
            // label17
            // 
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("Tahoma", 9F);
            this.label17.Location = new System.Drawing.Point(444, 11);
            this.label17.Name = "label17";
            this.label17.Size = new System.Drawing.Size(44, 14);
            this.label17.TabIndex = 4;
            this.label17.Text = "ธนาคาร";
            // 
            // label18
            // 
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.Location = new System.Drawing.Point(12, 10);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(88, 14);
            this.label18.TabIndex = 0;
            this.label18.Text = "จำนวนเงินในเช็ค";
            // 
            // chequeActualAmountTextBox
            // 
            this.chequeActualAmountTextBox.Location = new System.Drawing.Point(104, 5);
            this.chequeActualAmountTextBox.MaxLength = 16;
            this.chequeActualAmountTextBox.MaxLengthDecimalPoint = 2;
            this.chequeActualAmountTextBox.Name = "chequeActualAmountTextBox";
            this.chequeActualAmountTextBox.Size = new System.Drawing.Size(100, 22);
            this.chequeActualAmountTextBox.TabIndex = 1;
            this.chequeActualAmountTextBox.Text = "0.00";
            this.chequeActualAmountTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.chequeActualAmountTextBox.Click += new System.EventHandler(this.chequeActualAmountTextBox_Click);
            this.chequeActualAmountTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.chequeActualAmountTextBox_KeyDown);
            // 
            // panel7
            // 
            this.panel7.Controls.Add(this.editIcom);
            this.panel7.Controls.Add(this.cancelButton);
            this.panel7.Controls.Add(this.addEditButton);
            this.panel7.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel7.Location = new System.Drawing.Point(3, 140);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(954, 31);
            this.panel7.TabIndex = 1;
            // 
            // editIcom
            // 
            this.editIcom.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.editIcom.Image = global::PEA.BPM.CashManagementModule.Properties.Resources.EditTableHS;
            this.editIcom.Location = new System.Drawing.Point(928, 6);
            this.editIcom.Name = "editIcom";
            this.editIcom.Size = new System.Drawing.Size(16, 16);
            this.editIcom.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.editIcom.TabIndex = 37;
            this.editIcom.TabStop = false;
            this.editIcom.Visible = false;
            // 
            // cancelButton
            // 
            this.cancelButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.cancelButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.cancelButton.Location = new System.Drawing.Point(100, 4);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(94, 25);
            this.cancelButton.TabIndex = 1;
            this.cancelButton.Text = "ยกเลิก";
            this.cancelButton.UseVisualStyleBackColor = false;
            this.cancelButton.Click += new System.EventHandler(this.cancelButton_Click);
            // 
            // addEditButton
            // 
            this.addEditButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.addEditButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.addEditButton.Location = new System.Drawing.Point(0, 4);
            this.addEditButton.Name = "addEditButton";
            this.addEditButton.Size = new System.Drawing.Size(94, 25);
            this.addEditButton.TabIndex = 0;
            this.addEditButton.Text = "เพิ่ม";
            this.addEditButton.UseVisualStyleBackColor = false;
            this.addEditButton.Click += new System.EventHandler(this.addEditButton_Click);
            // 
            // paymentDataGridView
            // 
            this.paymentDataGridView.AllowUserToAddRows = false;
            this.paymentDataGridView.AllowUserToDeleteRows = false;
            this.paymentDataGridView.AllowUserToResizeRows = false;
            this.paymentDataGridView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.paymentDataGridView.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.paymentDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.paymentDataGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.methodNameDgColumn,
            this.Column6,
            this.Amount,
            this.EditButton,
            this.deleteButton,
            this.BankKey,
            this.ChqNo,
            this.ChqAccNo,
            this.ChqDt,
            this.PtId});
            this.paymentDataGridView.GridColor = System.Drawing.SystemColors.ControlLight;
            this.paymentDataGridView.Location = new System.Drawing.Point(6, 21);
            this.paymentDataGridView.MultiSelect = false;
            this.paymentDataGridView.Name = "paymentDataGridView";
            this.paymentDataGridView.ReadOnly = true;
            this.paymentDataGridView.RowHeadersVisible = false;
            this.paymentDataGridView.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.paymentDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.paymentDataGridView.Size = new System.Drawing.Size(954, 101);
            this.paymentDataGridView.TabIndex = 1;
            this.paymentDataGridView.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.paymentDataGridView_CellDoubleClick);
            this.paymentDataGridView.RowsAdded += new System.Windows.Forms.DataGridViewRowsAddedEventHandler(this.paymentDataGridView_RowsAdded);
            this.paymentDataGridView.RowsRemoved += new System.Windows.Forms.DataGridViewRowsRemovedEventHandler(this.paymentDataGridView_RowsRemoved);
            this.paymentDataGridView.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.paymentDataGridView_CellContentClick);
            // 
            // methodNameDgColumn
            // 
            this.methodNameDgColumn.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.methodNameDgColumn.DataPropertyName = "PtName";
            this.methodNameDgColumn.FillWeight = 1F;
            this.methodNameDgColumn.HeaderText = "ประเภทเงิน";
            this.methodNameDgColumn.MinimumWidth = 100;
            this.methodNameDgColumn.Name = "methodNameDgColumn";
            this.methodNameDgColumn.ReadOnly = true;
            // 
            // Column6
            // 
            this.Column6.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.Column6.DataPropertyName = "Description";
            this.Column6.FillWeight = 1F;
            this.Column6.HeaderText = "รายละเอียด";
            this.Column6.MinimumWidth = 350;
            this.Column6.Name = "Column6";
            this.Column6.ReadOnly = true;
            // 
            // Amount
            // 
            this.Amount.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.Amount.DataPropertyName = "Amount";
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle1.Format = "N2";
            dataGridViewCellStyle1.NullValue = null;
            this.Amount.DefaultCellStyle = dataGridViewCellStyle1;
            this.Amount.FillWeight = 1F;
            this.Amount.HeaderText = "จำนวนเงิน";
            this.Amount.MinimumWidth = 160;
            this.Amount.Name = "Amount";
            this.Amount.ReadOnly = true;
            this.Amount.Width = 160;
            // 
            // EditButton
            // 
            this.EditButton.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.EditButton.HeaderText = "";
            this.EditButton.Image = global::PEA.BPM.CashManagementModule.Properties.Resources.EditTableHS;
            this.EditButton.MinimumWidth = 30;
            this.EditButton.Name = "EditButton";
            this.EditButton.ReadOnly = true;
            this.EditButton.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.EditButton.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            this.EditButton.ToolTipText = "แก้ไขรายการ";
            this.EditButton.Width = 30;
            // 
            // deleteButton
            // 
            this.deleteButton.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.DisplayedCells;
            this.deleteButton.FillWeight = 1F;
            this.deleteButton.HeaderText = "";
            this.deleteButton.Image = global::PEA.BPM.CashManagementModule.Properties.Resources.Delete;
            this.deleteButton.MinimumWidth = 30;
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.ReadOnly = true;
            this.deleteButton.Resizable = System.Windows.Forms.DataGridViewTriState.True;
            this.deleteButton.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
            this.deleteButton.ToolTipText = "ลบรายการ";
            this.deleteButton.Width = 30;
            // 
            // BankKey
            // 
            this.BankKey.DataPropertyName = "BankKey";
            this.BankKey.HeaderText = "BankKey";
            this.BankKey.Name = "BankKey";
            this.BankKey.ReadOnly = true;
            this.BankKey.Visible = false;
            // 
            // ChqNo
            // 
            this.ChqNo.DataPropertyName = "ChqNo";
            this.ChqNo.HeaderText = "ChqNo";
            this.ChqNo.Name = "ChqNo";
            this.ChqNo.ReadOnly = true;
            this.ChqNo.Visible = false;
            // 
            // ChqAccNo
            // 
            this.ChqAccNo.DataPropertyName = "ChqAccNo";
            this.ChqAccNo.HeaderText = "ChqAccNo";
            this.ChqAccNo.Name = "ChqAccNo";
            this.ChqAccNo.ReadOnly = true;
            this.ChqAccNo.Visible = false;
            // 
            // ChqDt
            // 
            this.ChqDt.DataPropertyName = "ChqDt";
            this.ChqDt.HeaderText = "ChqDt";
            this.ChqDt.Name = "ChqDt";
            this.ChqDt.ReadOnly = true;
            this.ChqDt.Visible = false;
            // 
            // PtId
            // 
            this.PtId.DataPropertyName = "PtId";
            this.PtId.HeaderText = "PtId";
            this.PtId.Name = "PtId";
            this.PtId.ReadOnly = true;
            this.PtId.Visible = false;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.currentOpeningGb);
            this.groupBox1.Controls.Add(this.panel3);
            this.groupBox1.Controls.Add(this.groupBox3);
            this.groupBox1.Controls.Add(this.panel6);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.Location = new System.Drawing.Point(5, 5);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(972, 506);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "รายการปรับปรุงยอดยกมา";
            // 
            // currentOpeningGb
            // 
            this.currentOpeningGb.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.currentOpeningGb.Controls.Add(this.currentOpenGv);
            this.currentOpeningGb.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.currentOpeningGb.Location = new System.Drawing.Point(3, 46);
            this.currentOpeningGb.Name = "currentOpeningGb";
            this.currentOpeningGb.Size = new System.Drawing.Size(966, 76);
            this.currentOpeningGb.TabIndex = 7;
            this.currentOpeningGb.TabStop = false;
            this.currentOpeningGb.Text = "ยอดยกมาจากกะที่แล้ว";
            // 
            // currentOpenGv
            // 
            this.currentOpenGv.AllowUserToAddRows = false;
            this.currentOpenGv.AllowUserToDeleteRows = false;
            this.currentOpenGv.AllowUserToResizeRows = false;
            this.currentOpenGv.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.currentOpenGv.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.currentOpenGv.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.currentOpenGv.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.FlowDesc,
            this.CashAmtTxt,
            this.ChqAmtTxt,
            this.TotalAmt,
            this.dataGridViewTextBoxColumn1});
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.currentOpenGv.DefaultCellStyle = dataGridViewCellStyle5;
            this.currentOpenGv.GridColor = System.Drawing.SystemColors.ControlLight;
            this.currentOpenGv.Location = new System.Drawing.Point(5, 22);
            this.currentOpenGv.MultiSelect = false;
            this.currentOpenGv.Name = "currentOpenGv";
            this.currentOpenGv.ReadOnly = true;
            this.currentOpenGv.RowHeadersVisible = false;
            this.currentOpenGv.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.currentOpenGv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.currentOpenGv.Size = new System.Drawing.Size(955, 46);
            this.currentOpenGv.TabIndex = 6;
            this.currentOpenGv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.currentOpenGv_CellDoubleClick);
            this.currentOpenGv.Leave += new System.EventHandler(this.currentOpenGv_Leave);
            // 
            // FlowDesc
            // 
            this.FlowDesc.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.FlowDesc.DataPropertyName = "FlowDesc";
            this.FlowDesc.FillWeight = 1F;
            this.FlowDesc.HeaderText = "รายละเอียด";
            this.FlowDesc.MinimumWidth = 350;
            this.FlowDesc.Name = "FlowDesc";
            this.FlowDesc.ReadOnly = true;
            // 
            // CashAmtTxt
            // 
            this.CashAmtTxt.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.CashAmtTxt.DataPropertyName = "CashAmtTxt";
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle2.Format = "N2";
            dataGridViewCellStyle2.NullValue = null;
            this.CashAmtTxt.DefaultCellStyle = dataGridViewCellStyle2;
            this.CashAmtTxt.FillWeight = 1F;
            this.CashAmtTxt.HeaderText = "เงินสดยกมา";
            this.CashAmtTxt.MinimumWidth = 120;
            this.CashAmtTxt.Name = "CashAmtTxt";
            this.CashAmtTxt.ReadOnly = true;
            this.CashAmtTxt.Width = 120;
            // 
            // ChqAmtTxt
            // 
            this.ChqAmtTxt.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.ChqAmtTxt.DataPropertyName = "ChqAmtTxt";
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle3.Format = "N2";
            this.ChqAmtTxt.DefaultCellStyle = dataGridViewCellStyle3;
            this.ChqAmtTxt.FillWeight = 1F;
            this.ChqAmtTxt.HeaderText = "เช็คยกมา";
            this.ChqAmtTxt.MinimumWidth = 120;
            this.ChqAmtTxt.Name = "ChqAmtTxt";
            this.ChqAmtTxt.ReadOnly = true;
            this.ChqAmtTxt.Width = 120;
            // 
            // TotalAmt
            // 
            this.TotalAmt.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.TotalAmt.DataPropertyName = "SumAmtTxt";
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            dataGridViewCellStyle4.Format = "N2";
            this.TotalAmt.DefaultCellStyle = dataGridViewCellStyle4;
            this.TotalAmt.FillWeight = 1F;
            this.TotalAmt.HeaderText = "รวมยอดยกมา";
            this.TotalAmt.MinimumWidth = 120;
            this.TotalAmt.Name = "TotalAmt";
            this.TotalAmt.ReadOnly = true;
            this.TotalAmt.Width = 120;
            // 
            // dataGridViewTextBoxColumn1
            // 
            this.dataGridViewTextBoxColumn1.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.dataGridViewTextBoxColumn1.DataPropertyName = "PtName";
            this.dataGridViewTextBoxColumn1.FillWeight = 1F;
            this.dataGridViewTextBoxColumn1.HeaderText = "ยกมาจากวันที่";
            this.dataGridViewTextBoxColumn1.MinimumWidth = 120;
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn1.ReadOnly = true;
            this.dataGridViewTextBoxColumn1.Visible = false;
            this.dataGridViewTextBoxColumn1.Width = 120;
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.branchIdMaskedTextBox);
            this.panel3.Controls.Add(this.label11);
            this.panel3.Controls.Add(this.label6);
            this.panel3.Controls.Add(this.cashierCBox);
            this.panel3.Location = new System.Drawing.Point(3, 18);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(966, 28);
            this.panel3.TabIndex = 5;
            // 
            // branchIdMaskedTextBox
            // 
            this.branchIdMaskedTextBox.Location = new System.Drawing.Point(110, 3);
            this.branchIdMaskedTextBox.Name = "branchIdMaskedTextBox";
            this.branchIdMaskedTextBox.Size = new System.Drawing.Size(338, 22);
            this.branchIdMaskedTextBox.TabIndex = 41;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(53, 6);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(51, 14);
            this.label11.TabIndex = 40;
            this.label11.Text = "การไฟฟ้า";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(528, 6);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(98, 14);
            this.label6.TabIndex = 39;
            this.label6.Text = "แคชเชียร์ (เปิดกะ)";
            // 
            // cashierCBox
            // 
            this.cashierCBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.cashierCBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cashierCBox.FormattingEnabled = true;
            this.cashierCBox.Location = new System.Drawing.Point(632, 3);
            this.cashierCBox.Name = "cashierCBox";
            this.cashierCBox.Size = new System.Drawing.Size(318, 22);
            this.cashierCBox.TabIndex = 38;
            this.cashierCBox.SelectedIndexChanged += new System.EventHandler(this.cashierCBox_SelectedIndexChanged);
            // 
            // panel9
            // 
            this.panel9.BackColor = System.Drawing.Color.White;
            this.panel9.Controls.Add(this.groupBox1);
            this.panel9.Controls.Add(this.panel2);
            this.panel9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel9.Location = new System.Drawing.Point(10, 10);
            this.panel9.Name = "panel9";
            this.panel9.Padding = new System.Windows.Forms.Padding(5);
            this.panel9.Size = new System.Drawing.Size(982, 568);
            this.panel9.TabIndex = 2;
            // 
            // AdjustOpenBalanceView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(211, 117, 191);
            this.Controls.Add(this.panel9);
            this.Controls.Add(this.panel1);
            this.Name = "AdjustOpenBalanceView";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.Size = new System.Drawing.Size(1002, 588);
            this.panel6.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.inputGb.ResumeLayout(false);
            this.inputGb.PerformLayout();
            this.paymentTypeTabControl.ResumeLayout(false);
            this.cashTabPage.ResumeLayout(false);
            this.cashTabPage.PerformLayout();
            this.chequeTabPage.ResumeLayout(false);
            this.chequeTabPage.PerformLayout();
            this.panel7.ResumeLayout(false);
            this.panel7.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.editIcom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.paymentDataGridView)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.currentOpeningGb.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.currentOpenGv)).EndInit();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel9.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.TextBox totalAmtTxt;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Button cancelAllButton;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.DataGridView paymentDataGridView;
        private System.Windows.Forms.Panel panel9;
        private System.Windows.Forms.TextBox refNoTxt;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ComboBox flowCBox;
        private System.Windows.Forms.Button quiteBt;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ComboBox cashierCBox;
        private System.Windows.Forms.GroupBox inputGb;
        private System.Windows.Forms.TabControl paymentTypeTabControl;
        private System.Windows.Forms.TabPage cashTabPage;
        private PEA.BPM.Architecture.CommonUtilities.TextBoxDecimal cashAmountTextBox;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TabPage chequeTabPage;
        private System.Windows.Forms.Button chqBankSearchButton;
        private System.Windows.Forms.ComboBox chequeBankComboBox;
        private System.Windows.Forms.TextBox chqAccNoTxt;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.DateTimePicker chqDtPicker;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox chqNoTxt;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label17;
        private PEA.BPM.Architecture.CommonUtilities.TextBoxDecimal chequeActualAmountTextBox;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Panel panel7;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button addEditButton;
        private System.Windows.Forms.GroupBox groupBox6;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TextBox openBalanceNetTxt;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.DataGridView currentOpenGv;
        private System.Windows.Forms.GroupBox currentOpeningGb;
        private System.Windows.Forms.MaskedTextBox branchIdMaskedTextBox;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.DataGridViewTextBoxColumn FlowDesc;
        private System.Windows.Forms.DataGridViewTextBoxColumn CashAmtTxt;
        private System.Windows.Forms.DataGridViewTextBoxColumn ChqAmtTxt;
        private System.Windows.Forms.DataGridViewTextBoxColumn TotalAmt;
        private System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private System.Windows.Forms.PictureBox editIcom;
        private System.Windows.Forms.DataGridViewTextBoxColumn methodNameDgColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn Column6;
        private System.Windows.Forms.DataGridViewTextBoxColumn Amount;
        private System.Windows.Forms.DataGridViewImageColumn EditButton;
        private System.Windows.Forms.DataGridViewImageColumn deleteButton;
        private System.Windows.Forms.DataGridViewTextBoxColumn BankKey;
        private System.Windows.Forms.DataGridViewTextBoxColumn ChqNo;
        private System.Windows.Forms.DataGridViewTextBoxColumn ChqAccNo;
        private System.Windows.Forms.DataGridViewTextBoxColumn ChqDt;
        private System.Windows.Forms.DataGridViewTextBoxColumn PtId;









    }
}

