//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3615.
// 
#pragma warning disable 1591

namespace AdministrativeTool.OutOfShiftWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OutOfShiftWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class OutOfShiftWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelectOutOfShiftOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDBDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectCountOutOfShiftOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OutOfShiftWebService() {
            this.Url = global::AdministrativeTool.Properties.Settings.Default.AdministrativeTool_OutOfShiftWS_OutOfShiftWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelectOutOfShiftCompletedEventHandler SelectOutOfShiftCompleted;
        
        /// <remarks/>
        public event GetDBDateTimeCompletedEventHandler GetDBDateTimeCompleted;
        
        /// <remarks/>
        public event SelectCountOutOfShiftCompletedEventHandler SelectCountOutOfShiftCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectOutOfShift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectOutOfShift(System.DateTime startDt, System.DateTime endDt, string caseCode) {
            object[] results = this.Invoke("SelectOutOfShift", new object[] {
                        startDt,
                        endDt,
                        caseCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectOutOfShiftAsync(System.DateTime startDt, System.DateTime endDt, string caseCode) {
            this.SelectOutOfShiftAsync(startDt, endDt, caseCode, null);
        }
        
        /// <remarks/>
        public void SelectOutOfShiftAsync(System.DateTime startDt, System.DateTime endDt, string caseCode, object userState) {
            if ((this.SelectOutOfShiftOperationCompleted == null)) {
                this.SelectOutOfShiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOutOfShiftOperationCompleted);
            }
            this.InvokeAsync("SelectOutOfShift", new object[] {
                        startDt,
                        endDt,
                        caseCode}, this.SelectOutOfShiftOperationCompleted, userState);
        }
        
        private void OnSelectOutOfShiftOperationCompleted(object arg) {
            if ((this.SelectOutOfShiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectOutOfShiftCompleted(this, new SelectOutOfShiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDBDateTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetDBDateTime() {
            object[] results = this.Invoke("GetDBDateTime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetDBDateTimeAsync() {
            this.GetDBDateTimeAsync(null);
        }
        
        /// <remarks/>
        public void GetDBDateTimeAsync(object userState) {
            if ((this.GetDBDateTimeOperationCompleted == null)) {
                this.GetDBDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDBDateTimeOperationCompleted);
            }
            this.InvokeAsync("GetDBDateTime", new object[0], this.GetDBDateTimeOperationCompleted, userState);
        }
        
        private void OnGetDBDateTimeOperationCompleted(object arg) {
            if ((this.GetDBDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDBDateTimeCompleted(this, new GetDBDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SelectCountOutOfShift", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SelectCountOutOfShift(System.DateTime stDt, string caseCode) {
            object[] results = this.Invoke("SelectCountOutOfShift", new object[] {
                        stDt,
                        caseCode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SelectCountOutOfShiftAsync(System.DateTime stDt, string caseCode) {
            this.SelectCountOutOfShiftAsync(stDt, caseCode, null);
        }
        
        /// <remarks/>
        public void SelectCountOutOfShiftAsync(System.DateTime stDt, string caseCode, object userState) {
            if ((this.SelectCountOutOfShiftOperationCompleted == null)) {
                this.SelectCountOutOfShiftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectCountOutOfShiftOperationCompleted);
            }
            this.InvokeAsync("SelectCountOutOfShift", new object[] {
                        stDt,
                        caseCode}, this.SelectCountOutOfShiftOperationCompleted, userState);
        }
        
        private void OnSelectCountOutOfShiftOperationCompleted(object arg) {
            if ((this.SelectCountOutOfShiftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCountOutOfShiftCompleted(this, new SelectCountOutOfShiftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectOutOfShiftCompletedEventHandler(object sender, SelectOutOfShiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectOutOfShiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectOutOfShiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDBDateTimeCompletedEventHandler(object sender, GetDBDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDBDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDBDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SelectCountOutOfShiftCompletedEventHandler(object sender, SelectCountOutOfShiftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCountOutOfShiftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCountOutOfShiftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591