
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.PaymentCollectionModule
{
    partial class CustomerSearchView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.PaymentCollectionModule.CustomerSearchViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.searchPanel = new System.Windows.Forms.Panel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.otherBranchByIdCheckBox = new System.Windows.Forms.CheckBox();
            this.clearSearchByIdButton = new System.Windows.Forms.Button();
            this.searchByIdButton = new System.Windows.Forms.Button();
            this.customerIdMaskedTextBox = new System.Windows.Forms.MaskedTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.searchPanel.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // searchPanel
            // 
            this.searchPanel.BackColor = System.Drawing.Color.White;
            this.searchPanel.Controls.Add(this.groupBox2);
            this.searchPanel.Controls.Add(this.label1);
            this.searchPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.searchPanel.Location = new System.Drawing.Point(9, 9);
            this.searchPanel.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.searchPanel.Name = "searchPanel";
            this.searchPanel.Size = new System.Drawing.Size(213, 155);
            this.searchPanel.TabIndex = 1;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.otherBranchByIdCheckBox);
            this.groupBox2.Controls.Add(this.clearSearchByIdButton);
            this.groupBox2.Controls.Add(this.searchByIdButton);
            this.groupBox2.Controls.Add(this.customerIdMaskedTextBox);
            this.groupBox2.Location = new System.Drawing.Point(9, 39);
            this.groupBox2.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.groupBox2.Size = new System.Drawing.Size(193, 104);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "หมายเลขผู้ใช้ไฟ/บาร์โค้ด/รหัสลูกหนี้";
            // 
            // otherBranchByIdCheckBox
            // 
            this.otherBranchByIdCheckBox.AutoSize = true;
            this.otherBranchByIdCheckBox.Location = new System.Drawing.Point(18, 47);
            this.otherBranchByIdCheckBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.otherBranchByIdCheckBox.Name = "otherBranchByIdCheckBox";
            this.otherBranchByIdCheckBox.Size = new System.Drawing.Size(67, 17);
            this.otherBranchByIdCheckBox.TabIndex = 1;
            this.otherBranchByIdCheckBox.Text = "ต่างสาขา";
            this.otherBranchByIdCheckBox.UseVisualStyleBackColor = true;
            // 
            // clearSearchByIdButton
            // 
            this.clearSearchByIdButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.clearSearchByIdButton.Location = new System.Drawing.Point(99, 70);
            this.clearSearchByIdButton.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.clearSearchByIdButton.Name = "clearSearchByIdButton";
            this.clearSearchByIdButton.Size = new System.Drawing.Size(75, 22);
            this.clearSearchByIdButton.TabIndex = 3;
            this.clearSearchByIdButton.Text = "ล้างค่า";
            this.clearSearchByIdButton.UseVisualStyleBackColor = false;
            this.clearSearchByIdButton.Click += new System.EventHandler(this.clearSearchByIdButton_Click);
            // 
            // searchByIdButton
            // 
            this.searchByIdButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.searchByIdButton.Location = new System.Drawing.Point(18, 70);
            this.searchByIdButton.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.searchByIdButton.Name = "searchByIdButton";
            this.searchByIdButton.Size = new System.Drawing.Size(75, 22);
            this.searchByIdButton.TabIndex = 2;
            this.searchByIdButton.Text = "ค้นหา";
            this.searchByIdButton.UseVisualStyleBackColor = false;
            this.searchByIdButton.Click += new System.EventHandler(this.searchByIdButton_Click);
            // 
            // customerIdMaskedTextBox
            // 
            this.customerIdMaskedTextBox.Location = new System.Drawing.Point(18, 21);
            this.customerIdMaskedTextBox.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.customerIdMaskedTextBox.Name = "customerIdMaskedTextBox";
            this.customerIdMaskedTextBox.Size = new System.Drawing.Size(157, 21);
            this.customerIdMaskedTextBox.TabIndex = 0;
            this.customerIdMaskedTextBox.TextMaskFormat = System.Windows.Forms.MaskFormat.ExcludePromptAndLiterals;
            this.customerIdMaskedTextBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.customerIdMaskedTextBox_KeyPress);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.label1.Location = new System.Drawing.Point(7, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(103, 14);
            this.label1.TabIndex = 1;
            this.label1.Text = "ค้นหาข้อมูลลูกหนี้";
            // 
            // CustomerSearchView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(211, 117, 191);
            this.Controls.Add(this.searchPanel);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Name = "CustomerSearchView";
            this.Padding = new System.Windows.Forms.Padding(9);
            this.Size = new System.Drawing.Size(231, 673);
            this.searchPanel.ResumeLayout(false);
            this.searchPanel.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel searchPanel;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.CheckBox otherBranchByIdCheckBox;
        private System.Windows.Forms.Button clearSearchByIdButton;
        private System.Windows.Forms.Button searchByIdButton;
        private System.Windows.Forms.MaskedTextBox customerIdMaskedTextBox;
        private System.Windows.Forms.Label label1;
    }
}

