//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEA.BPM.ePaymentsModule.SG.EPayBillingWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Infrastructure.Interface.Business" +
        "Entities")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClearingAccNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupBankNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankKey {
            get {
                return this.BankKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.BankKeyField, value) != true)) {
                    this.BankKeyField = value;
                    this.RaisePropertyChanged("BankKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessPlace {
            get {
                return this.BusinessPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPlaceField, value) != true)) {
                    this.BusinessPlaceField = value;
                    this.RaisePropertyChanged("BusinessPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearingAccNo {
            get {
                return this.ClearingAccNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClearingAccNoField, value) != true)) {
                    this.ClearingAccNoField = value;
                    this.RaisePropertyChanged("ClearingAccNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupBankName {
            get {
                return this.GroupBankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupBankNameField, value) != true)) {
                    this.GroupBankNameField = value;
                    this.RaisePropertyChanged("GroupBankName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="EPayBillingWCF.IEPayBillingWCFService")]
    [WCFExtras.Soap.SoapHeadersAttribute()]
    public interface IEPayBillingWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/UpdateBillMarkFlagService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/UpdateBillMarkFlagServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/UpdateBillMarkFlagServiceBPMApplication" +
            "ExceptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        string UpdateBillMarkFlagService(string caId, string invoiceNo, string modifiedBy, string postServerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/DelBillMarkFlagService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/DelBillMarkFlagServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/DelBillMarkFlagServiceBPMApplicationExc" +
            "eptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        void DelBillMarkFlagService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/SearchDebtService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/SearchDebtServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/SearchDebtServiceBPMApplicationExceptio" +
            "nInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData SearchDebtService(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.SearchDebtParam searchDebtParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/SearchBPMDebtClearify", ReplyAction="http://tempuri.org/IEPayBillingWCFService/SearchBPMDebtClearifyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/SearchBPMDebtClearifyBPMApplicationExce" +
            "ptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData SearchBPMDebtClearify(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.SearchDebtParam searchDebtParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/GetDebtComparableService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/GetDebtComparableServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/GetDebtComparableServiceBPMApplicationE" +
            "xceptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData GetDebtComparableService(string caInvoceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/SearchCompany", ReplyAction="http://tempuri.org/IEPayBillingWCFService/SearchCompanyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/SearchCompanyBPMApplicationExceptionInf" +
            "oFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData SearchCompany(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.Company compParm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/InsertEPayUploadService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/InsertEPayUploadServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/InsertEPayUploadServiceBPMApplicationEx" +
            "ceptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        void InsertEPayUploadService(PEA.BPM.Architecture.CommonUtilities.CompressData ePayFileCompress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/IsUploadFileNameExist", ReplyAction="http://tempuri.org/IEPayBillingWCFService/IsUploadFileNameExistResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/IsUploadFileNameExistBPMApplicationExce" +
            "ptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        bool IsUploadFileNameExist(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/GetAgentPaymentService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/GetAgentPaymentServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/GetAgentPaymentServiceBPMApplicationExc" +
            "eptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData GetAgentPaymentService(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.AgentPayment agentPayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/InsertAgentPaymentService", ReplyAction="http://tempuri.org/IEPayBillingWCFService/InsertAgentPaymentServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/InsertAgentPaymentServiceBPMApplication" +
            "ExceptionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        void InsertAgentPaymentService(PEA.BPM.Architecture.CommonUtilities.CompressData agentPayCompress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/PrintGreenBill", ReplyAction="http://tempuri.org/IEPayBillingWCFService/PrintGreenBillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/PrintGreenBillBPMApplicationExceptionIn" +
            "foFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData PrintGreenBill(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.ReceiptPrinting.ReceiptConditionParam param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/SaveClearify", ReplyAction="http://tempuri.org/IEPayBillingWCFService/SaveClearifyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/SaveClearifyBPMApplicationExceptionInfo" +
            "Fault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        bool SaveClearify(PEA.BPM.Architecture.CommonUtilities.CompressData saveClearifyCompress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/SearchAgentPayment", ReplyAction="http://tempuri.org/IEPayBillingWCFService/SearchAgentPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/SearchAgentPaymentBPMApplicationExcepti" +
            "onInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        PEA.BPM.Architecture.CommonUtilities.CompressData SearchAgentPayment(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.CancelPayment param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPayBillingWCFService/InsertCancelPayment", ReplyAction="http://tempuri.org/IEPayBillingWCFService/InsertCancelPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PEA.BPM.Architecture.ArchitectureInterface.BusinessEntities.BPMApplicationExceptionInfo), Action="http://tempuri.org/IEPayBillingWCFService/InsertCancelPaymentBPMApplicationExcept" +
            "ionInfoFault", Name="BPMApplicationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/PEA.BPM.Architecture.ArchitectureInterfac" +
            "e.BusinessEntities")]
        [WCFExtras.Soap.SoapHeaderAttribute("AuthInfoValue", typeof(PEA.BPM.Architecture.CommonUtilities.AuthInfo), Direction=WCFExtras.Soap.SoapHeaderDirection.In)]
        void InsertCancelPayment(PEA.BPM.Architecture.CommonUtilities.CompressData param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IEPayBillingWCFServiceChannel : PEA.BPM.ePaymentsModule.SG.EPayBillingWCF.IEPayBillingWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EPayBillingWCFServiceClient : System.ServiceModel.ClientBase<PEA.BPM.ePaymentsModule.SG.EPayBillingWCF.IEPayBillingWCFService>, PEA.BPM.ePaymentsModule.SG.EPayBillingWCF.IEPayBillingWCFService {
        
        public EPayBillingWCFServiceClient() {
        }
        
        public EPayBillingWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EPayBillingWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPayBillingWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPayBillingWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateBillMarkFlagService(string caId, string invoiceNo, string modifiedBy, string postServerId) {
            return base.Channel.UpdateBillMarkFlagService(caId, invoiceNo, modifiedBy, postServerId);
        }
        
        public void DelBillMarkFlagService() {
            base.Channel.DelBillMarkFlagService();
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData SearchDebtService(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.SearchDebtParam searchDebtParam) {
            return base.Channel.SearchDebtService(searchDebtParam);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData SearchBPMDebtClearify(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.SearchDebtParam searchDebtParam) {
            return base.Channel.SearchBPMDebtClearify(searchDebtParam);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData GetDebtComparableService(string caInvoceNo) {
            return base.Channel.GetDebtComparableService(caInvoceNo);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData SearchCompany(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.Company compParm) {
            return base.Channel.SearchCompany(compParm);
        }
        
        public void InsertEPayUploadService(PEA.BPM.Architecture.CommonUtilities.CompressData ePayFileCompress) {
            base.Channel.InsertEPayUploadService(ePayFileCompress);
        }
        
        public bool IsUploadFileNameExist(string fileName) {
            return base.Channel.IsUploadFileNameExist(fileName);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData GetAgentPaymentService(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.AgentPayment agentPayment) {
            return base.Channel.GetAgentPaymentService(agentPayment);
        }
        
        public void InsertAgentPaymentService(PEA.BPM.Architecture.CommonUtilities.CompressData agentPayCompress) {
            base.Channel.InsertAgentPaymentService(agentPayCompress);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData PrintGreenBill(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.ReceiptPrinting.ReceiptConditionParam param) {
            return base.Channel.PrintGreenBill(param);
        }
        
        public bool SaveClearify(PEA.BPM.Architecture.CommonUtilities.CompressData saveClearifyCompress) {
            return base.Channel.SaveClearify(saveClearifyCompress);
        }
        
        public PEA.BPM.Architecture.CommonUtilities.CompressData SearchAgentPayment(PEA.BPM.ePaymentsModule.Interface.BusinessEntities.CancelPayment param) {
            return base.Channel.SearchAgentPayment(param);
        }
        
        public void InsertCancelPayment(PEA.BPM.Architecture.CommonUtilities.CompressData param) {
            base.Channel.InsertCancelPayment(param);
        }
    }
}
