//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// A presenter calls methods of a view to update the information that the view displays. 
// The view exposes its methods through an interface definition, and the presenter contains
// a reference to the view interface. This allows you to test the presenter with different 
// implementations of a view (for example, a mock view).
//
// For more information see:
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

using System;
using Microsoft.Practices.ObjectBuilder;
using Microsoft.Practices.CompositeUI;
using PEA.BPM.Infrastructure.Interface;
using Microsoft.Practices.CompositeUI.EventBroker;
using System.Collections.Generic;
using System.Windows.Forms;
using PEA.BPM.ePaymentsModule.Interface.Services;
using PEA.BPM.ePaymentsModule.Interface.Constants;
using PEA.BPM.ePaymentsModule.Interface.BusinessEntities.Reports;
using PEA.BPM.ePaymentsModule.Interface.BusinessEntities;
using PEA.BPM.ePaymentsModule.Services;


namespace PEA.BPM.ePaymentsModule
{
    public class RE_02CriteriaViewPresenter : Presenter<IRE_02CriteriaView>
    {

        public override void OnViewReady()
        {
            base.OnViewReady();
        }

        public void OnCloseView()
        {
            base.CloseView();
        }

        #region Publication Event

        [EventPublication(EventTopicNames.RE_02Report, PublicationScope.WorkItem)]
        public event EventHandler<EventArgs<RE02ParamInfo>> RE_02Report;
        internal void OnRE_02Report(RE02ParamInfo param)
        {
            if (RE_02Report != null)
                RE_02Report(this, new EventArgs<RE02ParamInfo>(param));
        }


        [EventPublication(EventTopicNames.LoadAccountClassList, PublicationScope.WorkItem)]
        public event EventHandler<EventArgs<ReportName>> LoadAccountClassListHandler;
        public void LoadAccountClassList(ReportName reportName)
        {
            if (LoadAccountClassListHandler != null)
            {
                LoadAccountClassListHandler(this, new EventArgs<ReportName>(reportName));
            }
        }


        [EventPublication(EventTopicNames.LoadCompanyList, PublicationScope.WorkItem)]
        public event EventHandler<EventArgs<CompanyParamInfo>> LoadCompanyListHandler;
        public void LoadCompanyList(CompanyParamInfo comParam)
        {
            if (LoadCompanyListHandler != null)
            {
                LoadCompanyListHandler(this, new EventArgs<CompanyParamInfo>(comParam));
            }
        }       
        
        #endregion

    }
}

