//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Foundational Module" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-290-Automation%20Add%20Foundational%20Module.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.BillPrintingModule.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames : PEA.BPM.BillPrintingModule.Interface.Constants.EventTopicNames
    {
        public const string PrintDualBill = "PrintDualBill";
        public const string PrintA4Bill = "PrintA4Bill";
        public const string ReprintDualBill = "ReprintDualBill";
        public const string PrintGroupInvoice = "PrintGroupInvoice";
        public const string ReprintGroupInvoice = "ReprintGroupInvoice";
        public const string PrintCoverPageGroupInvoice = "PrintCoverPageGroupInvoice";
        public const string PrintGreenBill = "PrintGreenBill";
        public const string RePrintBillByBank = "RePrintBillByBank";
        public const string PrintBillDeliveryReport = "PrintBillDeliveryReport";
        public const string PrintDailyPrintReport = "PrintDailyPrintReport";
        public const string PrintDailyUnprintReport = "PrintDailyUnprintReport";
        public const string PrintStreetRouteReceiveReport = "PrintStreetRouteReceiveReport";
        public const string PrintStreetRouteUnreceiveReport = "PrintStreetRouteUnreceiveReport";
        public const string PrintStreetRouteReport = "PrintStreetRouteReport";
        public const string PrintBillStatusReport = "PrintBillStatusReport";
        public const string PrintF16Report = "PrintF16Report";
        public const string GetGroupInvoiceRecords = "GetGroupInvoiceRecords";
        public const string PrintUnlockingLogReport = "PrintUnlockingLogReport";
        public const string GetGreenBillRecords = "GetGreenBillRecords";
        public const string PrintCoverPageGreenBillByBank = "PrintCoverPageGreenBillByBank";
        public const string PrintGrpInvSpecialBill = "PrintGrpInvSpecialBill";
        public const string CloseBillProcessingList = "CloseBillProcessingList";
        public const string GetPortion = "GetPortion";
        public const string GrpInvAvailableBillCount = "GrpInvAvailableBillCount";
        public const string InitBillDeliveryUI = "InitBillDeliveryUI";
        public const string FreezePanel = "FreezePanel";
        public const string ShowBlankReport = "ShowBlankReport";
        public const string GetBank = "GetBank";
        public const string CAUnprintReport = "CAUnprintReport";
        public const string DirectDebitStatusReport = "DirectDebitStatusReport";

        //new added March, 17
        public const string GrpInvSummaryReport = "GrpInvSummaryReport";
        public const string BlueByBankReport = "BlueByBankReport";
        public const string GreenByBankReport = "GreenByBankReport";
        public const string GroupingCrossCheckReport = "GroupingCrossCheckReport";
        public const string WaitCursor = "WaitCursor";

        //new added June, 02
        public const string LoadApprover = "LoadApprover";
        public const string ApproverUpdated = "ApproverUpdated";
        public const string DeliveryToUpdated = "DeliveryToUpdated";

        //new added June, 09
        //implemented the logic for swaping between left view and right view in printing the selected bill in 2nd data grid
        public const string ChangeStatusForLeftView = "ChangeStatusForLeftView";
        public const string PrintSelectedBill = "PrintSelectedBill";
        public const string ClearBillProcessingListView = "ClearBillProcessingListView";
        
        //new added November, 10
        public const string PrintGreenReceipt = "PrintGreenReceipt";
        public const string ReprintGreenReceipt = "ReprintGreenReceipt";
        
    }
}