
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.scsf.2006jun/SCSF/html/03-030-Model%20View%20Presenter%20%20MVP%20.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace PEA.BPM.PaymentCollectionModule
{
    partial class CAC06CriteriaView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private PEA.BPM.PaymentCollectionModule.CAC06CriteriaViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.searchPanel = new System.Windows.Forms.Panel();
            this.label3 = new System.Windows.Forms.Label();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.branchIdMaskedTextBox = new System.Windows.Forms.MaskedTextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.otherSiteReportRadioButton = new System.Windows.Forms.RadioButton();
            this.officeSiteRadioButton = new System.Windows.Forms.RadioButton();
            this.sortingGroupBox = new System.Windows.Forms.GroupBox();
            this.controllerSortingRadioButton = new System.Windows.Forms.RadioButton();
            this.branchIdSortingRadioButton = new System.Windows.Forms.RadioButton();
            this.transactionFromDateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.label2 = new System.Windows.Forms.Label();
            this.displayReportButton = new System.Windows.Forms.Button();
            this.collectorIdMaskedTextBox = new System.Windows.Forms.MaskedTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.searchPanel.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.sortingGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // searchPanel
            // 
            this.searchPanel.BackColor = System.Drawing.Color.White;
            this.searchPanel.Controls.Add(this.label3);
            this.searchPanel.Controls.Add(this.groupBox1);
            this.searchPanel.Controls.Add(this.label1);
            this.searchPanel.Location = new System.Drawing.Point(10, 10);
            this.searchPanel.Name = "searchPanel";
            this.searchPanel.Size = new System.Drawing.Size(210, 398);
            this.searchPanel.TabIndex = 3;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.label3.Location = new System.Drawing.Point(7, 29);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(193, 16);
            this.label3.TabIndex = 4;
            this.label3.Text = "งานและการรับเงินแทนการไฟฟ้าอื่น";
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.branchIdMaskedTextBox);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.sortingGroupBox);
            this.groupBox1.Controls.Add(this.transactionFromDateTimePicker);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.displayReportButton);
            this.groupBox1.Controls.Add(this.collectorIdMaskedTextBox);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Location = new System.Drawing.Point(10, 50);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(193, 337);
            this.groupBox1.TabIndex = 3;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "เงื่อนไข";
            // 
            // branchIdMaskedTextBox
            // 
            this.branchIdMaskedTextBox.Location = new System.Drawing.Point(18, 40);
            this.branchIdMaskedTextBox.Name = "branchIdMaskedTextBox";
            this.branchIdMaskedTextBox.Size = new System.Drawing.Size(156, 20);
            this.branchIdMaskedTextBox.TabIndex = 1;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.otherSiteReportRadioButton);
            this.groupBox2.Controls.Add(this.officeSiteRadioButton);
            this.groupBox2.Location = new System.Drawing.Point(18, 157);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(156, 69);
            this.groupBox2.TabIndex = 33;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "รูปแบบรายงาน";
            // 
            // otherSiteReportRadioButton
            // 
            this.otherSiteReportRadioButton.AutoSize = true;
            this.otherSiteReportRadioButton.Location = new System.Drawing.Point(9, 42);
            this.otherSiteReportRadioButton.Name = "otherSiteReportRadioButton";
            this.otherSiteReportRadioButton.Size = new System.Drawing.Size(120, 17);
            this.otherSiteReportRadioButton.TabIndex = 8;
            this.otherSiteReportRadioButton.TabStop = true;
            this.otherSiteReportRadioButton.Text = "รับแทนการไฟฟ้าอื่น";
            this.otherSiteReportRadioButton.UseVisualStyleBackColor = true;
            this.otherSiteReportRadioButton.Click += new System.EventHandler(this.officeSiteRadioButton_Click);
            // 
            // officeSiteRadioButton
            // 
            this.officeSiteRadioButton.AutoSize = true;
            this.officeSiteRadioButton.Location = new System.Drawing.Point(9, 19);
            this.officeSiteRadioButton.Name = "officeSiteRadioButton";
            this.officeSiteRadioButton.Size = new System.Drawing.Size(89, 17);
            this.officeSiteRadioButton.TabIndex = 7;
            this.officeSiteRadioButton.TabStop = true;
            this.officeSiteRadioButton.Text = "รับที่สำนักงาน";
            this.officeSiteRadioButton.UseVisualStyleBackColor = true;
            this.officeSiteRadioButton.Click += new System.EventHandler(this.officeSiteRadioButton_Click);
            // 
            // sortingGroupBox
            // 
            this.sortingGroupBox.Controls.Add(this.controllerSortingRadioButton);
            this.sortingGroupBox.Controls.Add(this.branchIdSortingRadioButton);
            this.sortingGroupBox.Location = new System.Drawing.Point(18, 227);
            this.sortingGroupBox.Name = "sortingGroupBox";
            this.sortingGroupBox.Size = new System.Drawing.Size(156, 71);
            this.sortingGroupBox.TabIndex = 32;
            this.sortingGroupBox.TabStop = false;
            this.sortingGroupBox.Text = "เรียงลำดับ";
            this.sortingGroupBox.Visible = false;
            // 
            // controllerSortingRadioButton
            // 
            this.controllerSortingRadioButton.AutoSize = true;
            this.controllerSortingRadioButton.Location = new System.Drawing.Point(9, 42);
            this.controllerSortingRadioButton.Name = "controllerSortingRadioButton";
            this.controllerSortingRadioButton.Size = new System.Drawing.Size(63, 17);
            this.controllerSortingRadioButton.TabIndex = 6;
            this.controllerSortingRadioButton.TabStop = true;
            this.controllerSortingRadioButton.Text = "ผู้รับเงิน";
            this.controllerSortingRadioButton.UseVisualStyleBackColor = true;
            // 
            // branchIdSortingRadioButton
            // 
            this.branchIdSortingRadioButton.AutoSize = true;
            this.branchIdSortingRadioButton.Location = new System.Drawing.Point(9, 19);
            this.branchIdSortingRadioButton.Name = "branchIdSortingRadioButton";
            this.branchIdSortingRadioButton.Size = new System.Drawing.Size(89, 17);
            this.branchIdSortingRadioButton.TabIndex = 5;
            this.branchIdSortingRadioButton.TabStop = true;
            this.branchIdSortingRadioButton.Text = "รหัสการไฟฟ้า";
            this.branchIdSortingRadioButton.UseVisualStyleBackColor = true;
            // 
            // transactionFromDateTimePicker
            // 
            this.transactionFromDateTimePicker.CustomFormat = "dd/MM/yyyy";
            this.transactionFromDateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.transactionFromDateTimePicker.Location = new System.Drawing.Point(18, 128);
            this.transactionFromDateTimePicker.Name = "transactionFromDateTimePicker";
            this.transactionFromDateTimePicker.Size = new System.Drawing.Size(111, 20);
            this.transactionFromDateTimePicker.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(15, 111);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(64, 13);
            this.label2.TabIndex = 6;
            this.label2.Text = "วันที่รับชำระ";
            // 
            // displayReportButton
            // 
            this.displayReportButton.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.displayReportButton.Location = new System.Drawing.Point(18, 304);
            this.displayReportButton.Name = "displayReportButton";
            this.displayReportButton.Size = new System.Drawing.Size(85, 23);
            this.displayReportButton.TabIndex = 9;
            this.displayReportButton.Text = "แสดงรายงาน";
            this.displayReportButton.UseVisualStyleBackColor = false;
            this.displayReportButton.Click += new System.EventHandler(this.displayReportButton_Click);
            // 
            // collectorIdMaskedTextBox
            // 
            this.collectorIdMaskedTextBox.Location = new System.Drawing.Point(18, 83);
            this.collectorIdMaskedTextBox.Name = "collectorIdMaskedTextBox";
            this.collectorIdMaskedTextBox.Size = new System.Drawing.Size(156, 20);
            this.collectorIdMaskedTextBox.TabIndex = 2;
            this.collectorIdMaskedTextBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.collectorIdMaskedTextBox_KeyPress);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(15, 67);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(64, 13);
            this.label7.TabIndex = 2;
            this.label7.Text = "รหัสผู้รับเงิน";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(15, 24);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(55, 13);
            this.label6.TabIndex = 0;
            this.label6.Text = "รหัส กฟฟ.";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(222)));
            this.label1.Location = new System.Drawing.Point(7, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(201, 16);
            this.label1.TabIndex = 0;
            this.label1.Text = "รายงานรายละเอียดการรับเงินที่สำนัก";
            // 
            // CAC06CriteriaView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(211, 117, 191);
            this.Controls.Add(this.searchPanel);
            this.Name = "CAC06CriteriaView";
            this.Size = new System.Drawing.Size(230, 519);
            this.searchPanel.ResumeLayout(false);
            this.searchPanel.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.sortingGroupBox.ResumeLayout(false);
            this.sortingGroupBox.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel searchPanel;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button displayReportButton;
        private System.Windows.Forms.MaskedTextBox collectorIdMaskedTextBox;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.DateTimePicker transactionFromDateTimePicker;
        private System.Windows.Forms.GroupBox sortingGroupBox;
        private System.Windows.Forms.RadioButton controllerSortingRadioButton;
        private System.Windows.Forms.RadioButton branchIdSortingRadioButton;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.RadioButton otherSiteReportRadioButton;
        private System.Windows.Forms.RadioButton officeSiteRadioButton;
        private System.Windows.Forms.MaskedTextBox branchIdMaskedTextBox;
    }
}

